* opacity descriptor (mixed) for scene6_bg_A707 — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_sprite_mixed: fcb start_col,width,start_row,num_rows,opaque.
scene6_bg_A707_opacity_mixed:
        fcb     0,1,15,2,0
        fcb     0,2,12,3,0
        fcb     0,3,0,1,0
        fcb     0,3,11,1,0
        fcb     0,4,1,1,0
        fcb     0,4,3,1,0
        fcb     0,4,5,1,0
        fcb     0,4,7,1,0
        fcb     0,4,9,1,0
        fcb     0,5,17,1,1
        fcb     0,7,2,1,0
        fcb     0,7,4,1,0
        fcb     0,7,6,1,0
        fcb     0,7,8,1,0
        fcb     0,7,10,1,0
        fcb     1,4,16,1,1
        fcb     1,5,15,1,1
        fcb     2,4,14,1,1
        fcb     2,5,12,2,1
        fcb     3,2,0,1,1
        fcb     3,6,11,1,1
        fcb     4,5,1,1,1
        fcb     4,5,3,1,1
        fcb     4,5,5,1,1
        fcb     4,5,7,1,1
        fcb     4,5,9,1,1
        fcb     5,2,0,1,0
        fcb     5,3,16,2,0
        fcb     6,2,14,2,0
        fcb     7,1,12,2,0
        fcb     7,2,0,1,1
        fcb     7,2,2,1,1
        fcb     7,2,4,1,1
        fcb     7,2,6,1,1
        fcb     7,2,8,1,1
        fcb     7,2,10,1,1
        fcb     8,1,12,6,1
        fcb     0,0,0,0,0      ; terminator (width byte 0)
