* opacity descriptor (stencil) for scene6_bg_A6A6 — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_stencil_punch: 2D mask (height,width, h*w bytes; 11=black,00=keep).
*   cel-local (byte-aligned); a sub-byte-placed cel needs build-side mask shifting.
scene6_bg_A6A6_opacity_stencil:
        fcb     6,7
        fcb     $FF,$FF,$FF,$FF,$00,$00,$00  ; row 0
        fcb     $0F,$FF,$FF,$FF,$C0,$00,$00  ; row 1
        fcb     $03,$FF,$FF,$FF,$FF,$00,$00  ; row 2
        fcb     $00,$0F,$FF,$FF,$FF,$FC,$00  ; row 3
        fcb     $00,$03,$FF,$FF,$FF,$FF,$00  ; row 4
        fcb     $00,$00,$0F,$FF,$FF,$FF,$FC  ; row 5
