* opacity descriptor (stencil) for scene6_bg_A6D4 — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_stencil_punch: 2D mask (height,width, h*w bytes; 11=black,00=keep).
*   cel-local (byte-aligned); a sub-byte-placed cel needs build-side mask shifting.
scene6_bg_A6D4_opacity_stencil:
        fcb     5,9
        fcb     $0F,$C0,$00,$3F,$FF,$FC,$00,$00,$00  ; row 0
        fcb     $00,$30,$00,$00,$00,$03,$C0,$00,$00  ; row 1
        fcb     $00,$0F,$C0,$00,$00,$00,$FC,$00,$00  ; row 2
        fcb     $00,$00,$30,$00,$00,$00,$03,$C0,$00  ; row 3
        fcb     $00,$00,$0F,$FF,$FF,$FF,$FF,$FC,$00  ; row 4
