* opacity descriptor (masked) for scene6_bg_A68A — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_sprite_masked: one mask byte/column (11=opaque,00=keyed).
scene6_bg_A68A_opacity_mask:
        fcb     $FF,$FF,$FC
