* opacity descriptor (mixed) for scene6_bg_A68A — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_sprite_mixed: fcb start_col,width,start_row,num_rows,opaque.
scene6_bg_A68A_opacity_mixed:
        fcb     0,1,0,1,0
        fcb     0,2,1,1,0
        fcb     1,2,0,1,1
        fcb     2,1,1,1,1
        fcb     0,0,0,0,0      ; terminator (width byte 0)
