* opacity descriptor (stencil) for scene6_bg_A87B — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_stencil_punch: 2D mask (height,width, h*w bytes; 11=black,00=keep).
*   cel-local (byte-aligned); a sub-byte-placed cel needs build-side mask shifting.
scene6_bg_A87B_opacity_stencil:
        fcb     6,7
        fcb     $00,$00,$00,$FF,$FF,$00,$00  ; row 0
        fcb     $03,$FF,$00,$00,$0F,$C0,$00  ; row 1
        fcb     $00,$3F,$00,$FF,$FF,$00,$00  ; row 2
        fcb     $00,$00,$F0,$00,$0F,$FC,$00  ; row 3
        fcb     $00,$00,$3F,$FF,$FF,$FF,$00  ; row 4
        fcb     $00,$00,$00,$FF,$FF,$FF,$FC  ; row 5
