* opacity descriptor (mixed) for scene6_bg_A87B — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_sprite_mixed: fcb start_col,width,start_row,num_rows,opaque.
scene6_bg_A87B_opacity_mixed:
        fcb     0,1,1,2,0
        fcb     0,2,3,2,0
        fcb     0,3,0,1,0
        fcb     0,3,5,1,0
        fcb     1,1,1,2,1
        fcb     2,1,2,1,0
        fcb     2,1,3,1,1
        fcb     2,2,1,1,0
        fcb     2,4,4,1,1
        fcb     3,1,3,1,0
        fcb     3,2,0,1,1
        fcb     3,2,2,1,1
        fcb     3,4,5,1,1
        fcb     4,2,1,1,1
        fcb     4,2,3,1,1
        fcb     5,2,0,1,0
        fcb     5,2,2,1,0
        fcb     6,1,1,1,0
        fcb     6,1,3,2,0
        fcb     0,0,0,0,0      ; terminator (width byte 0)
