* opacity descriptor (mixed) for scene6_bg_archfill1 — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_sprite_mixed: fcb start_col,width,start_row,num_rows,opaque.
scene6_bg_archfill1_opacity_mixed:
        fcb     0,2,0,6,1
        fcb     0,0,0,0,0      ; terminator (width byte 0)
