* opacity descriptor (mixed) for scene6_bg_A877 — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_sprite_mixed: fcb start_col,width,start_row,num_rows,opaque.
scene6_bg_A877_opacity_mixed:
        fcb     0,1,0,1,0
        fcb     1,3,0,1,1
        fcb     0,0,0,0,0      ; terminator (width byte 0)
