* opacity descriptor (masked) for scene6_bg_A684 — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_sprite_masked: one mask byte/column (11=opaque,00=keyed).
scene6_bg_A684_opacity_mask:
        fcb     $FF,$FF,$FF,$F0
