* opacity descriptor (mixed) for scene6_bg_A82B — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_sprite_mixed: fcb start_col,width,start_row,num_rows,opaque.
scene6_bg_A82B_opacity_mixed:
        fcb     0,1,0,7,1
        fcb     1,2,5,2,0
        fcb     1,3,3,2,0
        fcb     1,4,0,3,0
        fcb     3,3,6,1,1
        fcb     3,8,5,1,1
        fcb     4,2,4,1,1
        fcb     4,7,3,1,1
        fcb     5,1,2,1,1
        fcb     5,2,0,1,1
        fcb     5,6,1,1,1
        fcb     6,2,2,1,0
        fcb     6,2,4,1,0
        fcb     6,2,6,1,0
        fcb     7,1,0,1,0
        fcb     8,3,0,1,1
        fcb     8,3,2,1,1
        fcb     8,3,4,1,1
        fcb     8,3,6,1,1
        fcb     0,0,0,0,0      ; terminator (width byte 0)
