* opacity descriptor (mixed) for scene6_bg_A7D1 — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_sprite_mixed: fcb start_col,width,start_row,num_rows,opaque.
scene6_bg_A7D1_opacity_mixed:
        fcb     0,1,0,10,1
        fcb     0,2,10,1,0
        fcb     1,2,7,3,0
        fcb     1,3,5,2,0
        fcb     1,4,2,3,0
        fcb     1,5,0,2,0
        fcb     2,4,10,1,1
        fcb     3,3,9,1,1
        fcb     3,4,7,2,1
        fcb     4,4,5,2,1
        fcb     5,4,2,3,1
        fcb     6,3,0,2,1
        fcb     6,4,9,2,0
        fcb     7,4,8,1,0
        fcb     7,6,7,1,0
        fcb     8,3,6,1,0
        fcb     8,5,5,1,0
        fcb     9,1,0,2,0
        fcb     9,2,2,1,0
        fcb     9,2,4,1,0
        fcb     9,4,3,1,0
        fcb     10,1,1,1,1
        fcb     10,3,10,1,1
        fcb     10,4,0,1,1
        fcb     10,4,9,1,1
        fcb     11,2,1,1,0
        fcb     11,3,2,1,1
        fcb     11,3,4,1,1
        fcb     11,3,6,1,1
        fcb     11,3,8,1,1
        fcb     13,1,10,1,0
        fcb     13,1,1,1,1
        fcb     13,1,3,1,1
        fcb     13,1,5,1,1
        fcb     13,1,7,1,1
        fcb     0,0,0,0,0      ; terminator (width byte 0)
