#!/usr/bin/env python3
"""
gen_climb_opacity.py — build-side opacity codegen for the climb draw path.

For each climb_crawl cel that is AUTHORED (an opacity.s sidecar exists beside it), read the
sidecar and emit its descriptor + a lookup-table entry into tests/scripted/scene6_climb_opacity_gen.s,
which the crawl driver includes and climb_controller.s consumes. converted/none cels emit nothing.

Descriptor byte formats match the HAL blits exactly:
  mixed  : fcb start_col,width,start_row,num_rows,opaque ... ; term fcb 0,0,0,0,0   (HAL_gfx_blit_sprite_mixed)
  masked : fcb <width mask bytes>                                                    (HAL_gfx_blit_sprite_masked)
  stencil: fcb height,width' ; h rows of width' mask bytes                           (HAL_gfx_blit_stencil_punch)

SUB-BYTE (load-bearing): the climb cels are placed sub-byte. mixed rides the underlying
transparent/opaque blits (they honor blit_subbyte) — emitted as-authored. stencil_punch is
BYTE-ALIGNED, so the cel-local 2D mask is PRE-SHIFTED RIGHT by the cel's placement sub (pixels),
widening by one byte, so a byte-aligned punch at the cel's byte-col lands on the authored pixels.
masked is byte-aligned only — a sub-byte-placed masked cel is surfaced (STOP), not silently shifted.
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "sprite_tool"))
from placement_table import Table, ROOT
from celio import Cel
import sidecar as SC
import opacity as O

OUT = os.path.join(ROOT, "tests", "scripted", "scene6_climb_opacity_gen.s")
TYPE = {"mixed": 1, "masked": 2, "stencil": 3}

def _shift_stencil(mask_rows, w, sub):
    """Shift each h x w cel-local mask row RIGHT by `sub` pixels (sub*2 bits) -> h x (w+1) bytes.
    sub==0 -> unchanged (byte-aligned already)."""
    if sub == 0:
        return mask_rows, w
    out = []
    for row in mask_rows:
        val = int.from_bytes(bytes(row), "big")          # w*8 bits, MSB = pixel 0
        val <<= (8 - 2 * sub)                             # place into a (w+1)*8-bit field
        out.append(list(val.to_bytes(w + 1, "big")))
    return out, w + 1

def main():
    t = Table()
    # cel_id -> placement sub (first occurrence in the climb_crawl animation)
    sub_of = {}
    for fr in t.anim.get("climb_crawl", []):
        for part in fr.parts:
            sub_of.setdefault(part.cel_id, part.sub)

    out, tbl, stops = [], [], []
    out.append("* tests/scripted/scene6_climb_opacity_gen.s — GENERATED by harness/tools/gen_climb_opacity.py")
    out.append("*   opacity descriptors for AUTHORED climb cels (read from their opacity.s sidecars on disk)")
    out.append("*   + cl_opacity_tbl the climb draw path scans. DO NOT EDIT. include-only; no org.")
    out.append("")
    for cel_id, sub in sub_of.items():
        cel_dir = os.path.dirname(t.cel_path(cel_id))
        sc = SC.read_sidecar(cel_dir)
        if not sc:                                        # converted/none -> no descriptor
            continue
        # RE-DERIVE from the sidecar's marks (robust: a stale/incomplete stored descriptor — e.g.
        # a pre-fix mixed sidecar that didn't cover colour-only bytes — is corrected here).
        cel = Cel(os.path.join(cel_dir, "converted.s"))
        kind, payload = O.derive(cel, O.decode_to_opacity(cel, sc[0], sc[1]))
        label = os.path.basename(cel_dir)                 # the cel's asm label
        desc = f"op_{cel_id}"
        if kind == "mixed":
            # coverage guard: the mixed blit draws ONLY its regions, so they MUST cover every
            # byte of the sprite or colours go undrawn (the white/orange-gap bug). STOP if not.
            covered = set()
            for sc_, w_, sr, nr, op in payload:
                for rr in range(sr, sr + nr):
                    for cc in range(sc_, sc_ + w_):
                        covered.add((rr, cc))
            miss = [(r, c) for r in range(cel.h) for c in range(cel.w) if (r, c) not in covered]
            if miss:
                stops.append(f"{cel_id}: mixed descriptor leaves {len(miss)} byte(s) uncovered "
                             f"(would render partially transparent) — STOP")
                continue
            out.append(f"{desc}:  ; mixed (full-sprite coverage; rides sub-byte via the underlying blits)")
            for sc_, w_, sr, nr, op in payload:
                out.append(f"        fcb     {sc_},{w_},{sr},{nr},{op}")
            out.append("        fcb     0,0,0,0,0")
        elif kind == "masked":
            if sub != 0:
                stops.append(f"{cel_id}: masked descriptor on a sub-byte cel (sub={sub}) — "
                             f"masked is byte-aligned only; STOP (re-author as stencil or verify)")
                continue
            out.append(f"{desc}:  ; masked (byte-aligned per-column mask)")
            out.append(f"        fcb     {','.join(f'${b:02X}' for b in payload)}")
        else:                                             # stencil: pre-shift by placement sub
            rows, w2 = _shift_stencil(payload, cel.w, sub)
            out.append(f"{desc}:  ; stencil (2D mask, pre-shifted right by sub={sub} px for byte-aligned punch)")
            out.append(f"        fcb     {cel.h},{w2}")
            for r, row in enumerate(rows):
                out.append(f"        fcb     {','.join(f'${b:02X}' for b in row)}  ; row {r}")
        tbl.append((label, TYPE[kind], desc))

    out.append("")
    out.append("cl_opacity_tbl:  ; {fdb cel; fcb type(1=mixed,2=masked,3=stencil); fdb desc}, term fdb 0")
    for label, ty, desc in tbl:
        out.append(f"        fdb     {label}")
        out.append(f"        fcb     {ty}")
        out.append(f"        fdb     {desc}")
    out.append("        fdb     0                       ; end")
    out.append("")

    if stops:
        for s in stops:
            print("STOP:", s, file=sys.stderr)
        sys.exit(2)

    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {OUT}: {len(tbl)} authored climb cel(s) -> {[l for l,_,_ in tbl]}")

if __name__ == "__main__":
    main()
