#!/usr/bin/env python3
"""
gen_scene6_placement.py — codegen the scene-6 placement table (§2F single-home).

Reads the human-readable text-source (content/scene6/scene6_placement.txt):
  [registry]  sprite_id  cel_file        -> derive w/h/start_col FROM the cel converted.s
  [placement] placement_id sprite_id x y -> the resolved placed col,row
Emits the assembly table the build reads (tests/scripted/scene6_placement_gen.s):
  reg_<id>:  fcb w, h, start_col     ; start_col PROMOTED from the cel comment to structured
  plc_<pid>: fcb x, y

The cel converted.s carries: `fcb h,w` (header, byte0=h byte1=w) and a comment `start_col=N`.
No manifest; the build reads only this generated table + the cel .s.
"""
import re, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC  = os.path.join(ROOT, "content", "scene6", "scene6_placement.txt")
OUT  = os.path.join(ROOT, "tests", "scripted", "scene6_placement_gen.s")

def parse_cel(cel_dir):
    """Return (w, h, start_col) derived from the cel's converted.s (h/w from `fcb h,w`, start_col from comment)."""
    f = os.path.join(ROOT, cel_dir, "converted.s")
    with open(f, encoding="utf-8", errors="replace") as fh:
        txt = fh.read()
    # header: first `fcb h,w` after the label line (h = rows, w = bytes/row)
    m = re.search(r"^\s*fcb\s+(\d+)\s*,\s*(\d+)", txt, re.M)
    if not m:
        raise SystemExit(f"no fcb h,w header in {f}")
    h, w = int(m.group(1)), int(m.group(2))
    sc = re.search(r"start_col=(\d+)", txt)
    start_col = int(sc.group(1)) if sc else 0
    return w, h, start_col

def main():
    registry = {}   # sprite_id -> cel_file
    placement = []  # (placement_id, sprite_id, x, y)
    section = None
    with open(SRC, encoding="utf-8") as fh:
        for line in fh:
            s = line.split("#", 1)[0].strip()
            if not s:
                continue
            if s == "[registry]":  section = "reg";  continue
            if s == "[placement]": section = "plc";  continue
            parts = s.split()
            if section == "reg":
                registry[parts[0]] = parts[1]
            elif section == "plc":
                placement.append((parts[0], parts[1], int(parts[2]), int(parts[3])))

    # derive registry dims/start_col from the cels
    reg = {sid: parse_cel(path) for sid, path in registry.items()}

    out = []
    out.append("* tests/scripted/scene6_placement_gen.s — GENERATED by harness/tools/gen_scene6_placement.py")
    out.append("*   from content/scene6/scene6_placement.txt. DO NOT EDIT. Edit the text-source, re-run the codegen.")
    out.append("*   The single-home (§2F) scene-6 placement table the build reads. include-only; no org.")
    out.append("* --- registry: reg_<id> = fcb w, h, start_col (start_col promoted from the cel comment) ---")
    for sid in registry:
        w, h, sc = reg[sid]
        out.append(f"reg_{sid}:  fcb {w},{h},{sc}   ; w, h, start_col")
    out.append("* --- placement: plc_<id> = fcb x, y (resolved placed col,row) ---")
    for pid, sid, x, y in placement:
        out.append(f"plc_{pid}:  fcb {x},{y}   ; {sid}: col, row")
    out.append("")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print(f"wrote {OUT}: {len(registry)} registry rows, {len(placement)} placement rows")

if __name__ == "__main__":
    main()
