#!/usr/bin/env python3
"""
gen_scene6_cliff.py — emit tests/scripted/scene6_cliff.s: the STATIC climb-tableau
cliff/scenery + player start-pose draw module for Stage 3.

Positions are the traced climb draw positions (Apple byte-col $05, sub-byte $10, row
$06) from the climb census. Each is mapped to a CoCo3 placement:

  Apple_X   = col*7 + sh
  CoCo3_X   = Apple_X + 20                (Stage-1 +20px centering: 280px in 320)
  byte      = (CoCo3_X >> 2) + L          (L = leading all-zero CoCo3 byte-cols the
  sub       = CoCo3_X & 3                  convert TRIMMED — re-derived here so the
  row       = row                          trimmed cel registers at its true column)

Emits a (fdb cel; fcb sub,byte,row) table + a draw loop for the scenery, and explicit
draws for the 2-part start pose. Composited AFTER the backdrop, BEFORE the HUD.
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from sprite_convert import convert_sprite_to_coco3
from stage0_convert_scene6 import load_dump, extract_cel
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))

# (label, addr, col, sh, row) — traced climb positions (col<0x28; wrap FF dropped).
AB8E_ROWS = list(range(0x75, 0x98, 2))          # cliff face striations, col$0A
SCENERY = []
SCENERY += [('scene6_cliff_AB8E', 0xAB8E, 0x0A, 0, r) for r in AB8E_ROWS]
SCENERY += [('scene6_cliff_AB94', 0xAB94, 0x0A, 0, 0x70)]
SCENERY += [('scene6_cliff_AB7C', 0xAB7C, 0x0A, 0, 0x68)]
SCENERY += [('scene6_cliff_AB4A', 0xAB4A, 0x00, 0, 0x70)]
SCENERY += [('scene6_cliff_AA7D', 0xAA7D, 0x06, 0, 0x98)]           # base
SCENERY += [('scene6_cliff_AA23', 0xAA23, c, 2, 0x64) for c in (0x0B, 0x17, 0x23)]
SCENERY += [('scene6_cliff_AA31', 0xAA31, c, 2, 0x64) for c in (0x0B, 0x17, 0x23)]
# start pose (crawl anchor): A3E9 legs (Y158 bottom) drawn first, A3C5 torso over it.
POSE = [('scene6_climb_A3E9', 0xA3E9, 0x09, 0, 0x9E),
        ('scene6_climb_A3C5', 0xA3C5, 0x0A, 0, 0x8D)]


def leading_trim(addr):
    """L = leading all-zero CoCo3 byte-columns the convert trimmed (geometry only —
    independent of start_col/flip: an ON pixel is non-zero at any parity)."""
    h, w, bitmap = extract_cel(load_dump(), addr)
    packed, cw = convert_sprite_to_coco3(bitmap, h, w, start_col=0)
    has = [any(packed[r * cw + c] != 0 for r in range(h)) for c in range(cw)]
    return next((i for i in range(cw) if has[i]), 0)


def place(col, sh, row, L):
    x = col * 7 + sh + 20
    return (x >> 2) + L, x & 3, row


def entries(items):
    out, seen_L = [], {}
    for label, addr, col, sh, row in items:
        if addr not in seen_L:
            seen_L[addr] = leading_trim(addr)
        byte, sub, r = place(col, sh, row, seen_L[addr])
        out.append((label, sub, byte, r))
    return out


def main():
    scn = entries(SCENERY)
    pose = entries(POSE)
    labels = sorted({e[0] for e in scn + pose})
    L = []
    L.append("* tests/scripted/scene6_cliff.s  — GENERATED by harness/tools/gen_scene6_cliff.py")
    L.append("* STATIC climb-tableau cliff/scenery + player start-pose. include-only.")
    L.append("* Composite order (driver): backdrop -> THIS (cliff/scenery -> start-pose) -> player-HUD.")
    L.append("* Positions = traced climb draw cols/rows -> CoCo3 (+20px centered, +leading-trim).")
    L.append("* ---------------------------------------------------------------")
    L.append("")
    L.append("* draw_climb_scenery — cliff face ($AB8E striations) + structure + base + mountain")
    L.append("*   band, table-driven. Transparent blit (index-0 keys to the backdrop behind).")
    L.append("draw_climb_scenery:")
    L.append("        ldy     #climb_scn_tbl")
    L.append("dcs_loop:")
    L.append("        ldx     ,y++                    ; X = cel ptr (0 = end)")
    L.append("        beq     dcs_done")
    L.append("        lda     ,y+                     ; sub-byte")
    L.append("        sta     <blit_subbyte")
    L.append("        lda     ,y+                     ; A = byte col")
    L.append("        ldb     ,y+                     ; B = row")
    L.append("        pshs    y")
    L.append("        jsr     HAL_gfx_blit_sprite")
    L.append("        puls    y")
    L.append("        bra     dcs_loop")
    L.append("dcs_done:")
    L.append("        rts")
    L.append("")
    L.append("* draw_climb_startpose — the 2-part crawl-start pose: legs $A3E9 (Y158) then")
    L.append("*   torso $A3C5 over it. Drawn AFTER scenery so the player is on top of the cliff.")
    L.append("draw_climb_startpose:")
    for label, sub, byte, row in pose:
        L.append(f"        lda     #{sub}")
        L.append(f"        sta     <blit_subbyte")
        L.append(f"        lda     #{byte}                     ; byte col")
        L.append(f"        ldb     #{row}                    ; row (Y={row})")
        L.append(f"        ldx     #{label}")
        L.append(f"        jsr     HAL_gfx_blit_sprite")
    L.append("        rts")
    L.append("")
    L.append("climb_scn_tbl:")
    for label, sub, byte, row in scn:
        L.append(f"        fdb     {label}")
        L.append(f"        fcb     {sub},{byte},{row}")
    L.append("        fdb     0                       ; end")
    L.append("")
    L.append("* --- cel data (single source) ---")
    for lab in labels:
        cat = 'player' if lab.startswith('scene6_climb_') else 'scenery'
        L.append(f'        include "../../content/{cat}/{lab}/converted.s"')
    L.append("")
    out = os.path.join(REPO, 'tests', 'scripted', 'scene6_cliff.s')
    open(out, 'w').write('\n'.join(L) + '\n')
    print("wrote", out)
    print(f"scenery draws: {len(scn)}  pose draws: {len(pose)}  cel includes: {len(labels)}")
    for label, sub, byte, row in pose:
        print(f"  POSE {label}: byte={byte} sub={sub} row={row}")


if __name__ == '__main__':
    main()
