#!/usr/bin/env python3
"""gen_arch_opacity.py — opacity STENCILS for the arch cels, for the static arch test.

The arch cels are placed sub-byte and the opaque/keyed boundaries can be sub-byte, so the uniform
representation is a STENCIL: a 2D mask (bit-pair 11 = punch black, 00 = leave) pre-shifted RIGHT by
the cel's placement sub, so a byte-aligned HAL_gfx_blit_stencil_punch lands on the authored pixels.
Draw path per opaque cel = plain transparent blit (colours + keyed black) THEN stencil-punch the
opaque black.

Reads the arch: block for each cel's placement sub, and the cel's opacity.s sidecar for the opaque
mask. Emits tests/scripted/scene6_arch_opacity_gen.s: per-cel stencils + arch_opacity_tbl
{fdb cel; fdb stencil} (0-terminated). Cels with no opaque pixels are omitted (plain blit only).
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "sprite_tool"))
from placement_table import Table, ROOT
from celio import Cel
import sidecar as SC
import opacity as O

OUT = os.path.join(ROOT, "tests", "scripted", "scene6_arch_opacity_gen.s")

def opaque_mask_rows(cel, opac):
    """h rows x cel.w bytes; each byte = 4 bit-pairs, 11 where index-0 pixel is opaque, else 00."""
    rows = []
    for r in range(cel.h):
        row = []
        for c in range(cel.w):
            b = 0
            for k in range(4):
                px = c * 4 + k
                if cel.pixels[r][px] == 0 and opac[r][px]:
                    b |= (0b11 << (6 - 2 * k))
            row.append(b)
        rows.append(row)
    return rows

def shift_right(rows, w, sub):
    """Shift each row's mask RIGHT by sub pixels (sub*2 bits) into a (w or w+1)-byte field."""
    if sub == 0:
        return rows, w
    out = []
    for row in rows:
        val = int.from_bytes(bytes(row), "big") << (8 - 2 * sub)
        out.append(list(val.to_bytes(w + 1, "big")))
    return out, w + 1

def main():
    t = Table()
    # placement sub per arch cel = the arch: a0 frame (halt reference $52=$1B)
    sub_of = {}
    for part in t.anim["arch"][0].parts:
        sub_of.setdefault(part.cel_id, part.sub)

    out, tbl = [], []
    out.append("* tests/scripted/scene6_arch_opacity_gen.s — GENERATED by harness/tools/gen_arch_opacity.py")
    out.append("*   pre-shifted opacity STENCILS for the arch cels (opaque index-0 black) + arch_opacity_tbl")
    out.append("*   the arch draw path scans. Punch is byte-aligned; masks pre-shifted by placement sub.")
    out.append("*   DO NOT EDIT. include-only; no org.")
    out.append("")
    for cel_id in sub_of:
        cel_dir = os.path.dirname(t.cel_path(cel_id))
        sc = SC.read_sidecar(cel_dir)
        if not sc:
            continue                                    # no opaque pixels -> plain blit only
        cel = Cel(os.path.join(cel_dir, "converted.s"))
        opac = O.decode_to_opacity(cel, sc[0], sc[1])
        rows = opaque_mask_rows(cel, opac)
        if not any(any(b for b in row) for row in rows):
            continue
        sub = sub_of[cel_id]
        rows2, w2 = shift_right(rows, cel.w, sub)
        label = os.path.basename(cel_dir)
        desc = f"aop_{cel_id}"
        out.append(f"{desc}:  ; stencil (opaque black), pre-shifted right by sub={sub}px")
        out.append(f"        fcb     {cel.h},{w2}")
        for r, row in enumerate(rows2):
            out.append(f"        fcb     {','.join(f'${b:02X}' for b in row)}  ; row {r}")
        tbl.append((label, desc))
    out.append("")
    out.append("arch_opacity_tbl:  ; {fdb cel; fdb stencil}, 0-terminated")
    for label, desc in tbl:
        out.append(f"        fdb     {label}")
        out.append(f"        fdb     {desc}")
    out.append("        fdb     0                       ; end")
    out.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {OUT}: {len(tbl)} arch cels with opaque stencils -> {[l.split('_')[-1] for l,_ in tbl]}")

if __name__ == "__main__":
    main()
