#!/usr/bin/env python3
"""gen_arch_opacity_mixed.py — MIXED opacity descriptors for the arch cels, for the SCROLLING driver.

The arch is $52-relative and its sub-byte placement changes every scroll step, so a pre-shifted
stencil (fixed sub) will not align. The MIXED blit (HAL_gfx_blit_sprite_mixed) rides blit_subbyte
natively, so it is the sub-byte-safe encoding. Mixed is BYTE-granular: a byte is opaque iff any of
its index-0 pixels is authored opaque; colour pixels are always drawn. This also keeps the full
index-0 PADDING columns transparent (they carry no opaque marks) -> no black padding lines.

Mixed requires FULL-sprite coverage (every byte in some region) or colours go undrawn. Emitted as
per-row runs of same-opacity bytes: fcb start_col,width,start_row,num_rows,opaque ; term 0,0,0,0,0.
Emits tests/scripted/scene6_arch_opacity_mixed_gen.s + arch_opacity_tbl {fdb cel; fdb desc}, 0-term.
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "sprite_tool"))
from placement_table import Table, ROOT
from celio import Cel
import sidecar as SC
import opacity as O

OUT = os.path.join(ROOT, "tests", "scripted", "scene6_arch_opacity_mixed_gen.s")

def byte_opaque(cel, opac):
    """h x w: True where the byte has an authored-opaque index-0 pixel (byte-granular)."""
    grid = []
    for r in range(cel.h):
        row = []
        for c in range(cel.w):
            op = any(cel.pixels[r][c*4+k] == 0 and opac[r][c*4+k] for k in range(4))
            row.append(op)
        grid.append(row)
    return grid

def main():
    t = Table()
    out, tbl = [], []
    out.append("* tests/scripted/scene6_arch_opacity_mixed_gen.s — GENERATED by gen_arch_opacity_mixed.py")
    out.append("*   MIXED opacity descriptors (byte-granular, full coverage) for the arch cels. The mixed")
    out.append("*   blit rides sub-byte, so this is the scroll-safe encoding. DO NOT EDIT. include-only.")
    out.append("")
    cel_ids = [p.cel_id for p in t.anim["arch"][0].parts]
    seen = set()
    for cel_id in cel_ids:
        if cel_id in seen:
            continue
        seen.add(cel_id)
        cel_dir = os.path.dirname(t.cel_path(cel_id))
        sc = SC.read_sidecar(cel_dir)
        if not sc:
            continue                                     # no opaque pixels -> plain blit
        cel = Cel(os.path.join(cel_dir, "converted.s"))
        opac = O.decode_to_opacity(cel, sc[0], sc[1])
        bo = byte_opaque(cel, opac)
        if not any(any(row) for row in bo):
            continue
        label = os.path.basename(cel_dir)
        desc = f"amx_{cel_id}"
        out.append(f"{desc}:  ; mixed (byte-granular, full coverage), rides sub-byte")
        # per row, emit runs of same-opacity bytes (full coverage)
        for r in range(cel.h):
            c = 0
            while c < cel.w:
                op = bo[r][c]; w = 1
                while c + w < cel.w and bo[r][c + w] == op:
                    w += 1
                out.append(f"        fcb     {c},{w},{r},1,{1 if op else 0}")
                c += w
        out.append("        fcb     0,0,0,0,0")
        tbl.append((label, desc))
    out.append("")
    out.append("arch_opacity_tbl:  ; {fdb cel; fdb mixed-desc}, 0-terminated")
    for label, desc in tbl:
        out.append(f"        fdb     {label}")
        out.append(f"        fdb     {desc}")
    out.append("        fdb     0")
    out.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {OUT}: {len(tbl)} arch cels with mixed opacity -> {[l.split('_')[-1] for l,_ in tbl]}")

if __name__ == "__main__":
    main()
