#!/usr/bin/env python3
"""gen_arch_opacity_scroll.py — per-SUB opacity STENCILS for the arch cels, for the SCROLLING driver.

The static arch test (gen_arch_opacity.py) reproduces Jay's authored opacity CLEANLY via a plain
transparent blit (colours + keyed black) THEN a byte-aligned punch of a stencil PRE-SHIFTED by the
cel's placement sub. The scroll changes the sub every step, so a single pre-shifted stencil won't
align — but sub is only ever 0..3, so we pre-generate ALL FOUR shifts per cel and let draw_arch pick
the one for the current sub. Same pixel-precise mask, same approved look, at any scroll position.

(The earlier MIXED-blit encoding was byte-granular and blitted each opacity region with its own
sub-byte overflow, which smeared black lines at region boundaries and blackened coarse bytes — the
"super dirty / black splotches / vertical lines" Jay saw. This stencil path avoids all of that.)

Reads the SAME opacity.s sidecars as gen_arch_opacity.py (Jay's authored, approved opacity). Emits
tests/scripted/scene6_arch_opacity_scroll_gen.s: per opaque cel, stencils aops_<cel>_s0..s3, and
arch_stencil_tbl: {fdb cel; fdb s0; fdb s1; fdb s2; fdb s3}, 0-terminated. Cels with no opaque
pixels are omitted (plain transparent blit only — keyed black).
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "sprite_tool"))
from placement_table import Table, ROOT
from celio import Cel
import sidecar as SC
import opacity as O

OUT = os.path.join(ROOT, "tests", "scripted", "scene6_arch_opacity_scroll_gen.s")


def opaque_mask_rows(cel, opac):
    """h rows x cel.w bytes; each byte = 4 bit-pairs, 11 where index-0 pixel is opaque, else 00."""
    rows = []
    for r in range(cel.h):
        row = []
        for c in range(cel.w):
            b = 0
            for k in range(4):
                px = c * 4 + k
                if cel.pixels[r][px] == 0 and opac[r][px]:
                    b |= (0b11 << (6 - 2 * k))
            row.append(b)
        rows.append(row)
    return rows


def shift_right(rows, w, sub):
    """Shift each row's mask RIGHT by sub pixels (sub*2 bits) into a (w or w+1)-byte field."""
    if sub == 0:
        return rows, w
    out = []
    for row in rows:
        val = int.from_bytes(bytes(row), "big") << (8 - 2 * sub)
        out.append(list(val.to_bytes(w + 1, "big")))
    return out, w + 1


def main():
    t = Table()
    # arch cel order = the arch: a0 frame (halt reference); de-dup preserving order
    cel_ids, seen = [], set()
    for part in t.anim["arch"][0].parts:
        if part.cel_id not in seen:
            seen.add(part.cel_id)
            cel_ids.append(part.cel_id)

    out, tbl = [], []
    out.append("* tests/scripted/scene6_arch_opacity_scroll_gen.s — GENERATED by gen_arch_opacity_scroll.py")
    out.append("*   per-SUB opacity STENCILS (opaque index-0 black) for the arch cels + arch_stencil_tbl.")
    out.append("*   Four pre-shifted stencils per cel (sub 0..3); draw_arch selects by the runtime sub.")
    out.append("*   Same pixel-precise masks as the approved static arch. DO NOT EDIT. include-only; no org.")
    out.append("")
    for cel_id in cel_ids:
        cel_dir = os.path.dirname(t.cel_path(cel_id))
        sc = SC.read_sidecar(cel_dir)
        if not sc:
            continue                                    # no opaque pixels -> plain trans blit only
        cel = Cel(os.path.join(cel_dir, "converted.s"))
        opac = O.decode_to_opacity(cel, sc[0], sc[1])
        rows0 = opaque_mask_rows(cel, opac)
        if not any(any(b for b in row) for row in rows0):
            continue
        label = os.path.basename(cel_dir)
        ptrs = []
        for sub in range(4):
            rows2, w2 = shift_right(rows0, cel.w, sub)
            desc = f"aops_{cel_id}_s{sub}"
            ptrs.append(desc)
            out.append(f"{desc}:  ; stencil pre-shifted right by sub={sub}px")
            out.append(f"        fcb     {cel.h},{w2}")
            for r, row in enumerate(rows2):
                out.append(f"        fcb     {','.join(f'${b:02X}' for b in row)}  ; row {r}")
        tbl.append((label, ptrs))
    out.append("")
    out.append("arch_stencil_tbl:  ; {fdb cel; fdb s0; fdb s1; fdb s2; fdb s3}, 0-terminated")
    for label, ptrs in tbl:
        out.append(f"        fdb     {label}")
        out.append("        fdb     " + ",".join(ptrs))
    out.append("        fdb     0                       ; end")
    out.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {OUT}: {len(tbl)} arch cels x4 subs -> {[l.split('_')[-1] for l,_ in tbl]}")


if __name__ == "__main__":
    main()
