* opacity descriptor (mixed) for scene6_bg_A6C0 — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_sprite_mixed: fcb start_col,width,start_row,num_rows,opaque.
scene6_bg_A6C0_opacity_mixed:
        fcb     0,1,0,2,0
        fcb     0,2,2,2,0
        fcb     0,3,4,2,0
        fcb     1,3,0,2,1
        fcb     2,2,2,2,1
        fcb     3,1,4,2,1
        fcb     0,0,0,0,0      ; terminator (width byte 0)
