* opacity descriptor (stencil) for scene6_bg_A6C0 — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_stencil_punch: 2D mask (height,width, h*w bytes; 11=black,00=keep).
*   cel-local (byte-aligned); a sub-byte-placed cel needs build-side mask shifting.
scene6_bg_A6C0_opacity_stencil:
        fcb     6,4
        fcb     $00,$FF,$00,$00  ; row 0
        fcb     $00,$03,$00,$00  ; row 1
        fcb     $00,$00,$FC,$00  ; row 2
        fcb     $00,$00,$03,$00  ; row 3
        fcb     $00,$00,$00,$FC  ; row 4
        fcb     $00,$00,$00,$03  ; row 5
