* opacity descriptor (stencil) for scene6_bg_A865 — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_stencil_punch: 2D mask (height,width, h*w bytes; 11=black,00=keep).
*   cel-local (byte-aligned); a sub-byte-placed cel needs build-side mask shifting.
scene6_bg_A865_opacity_stencil:
        fcb     8,4
        fcb     $00,$00,$03,$C0  ; row 0
        fcb     $00,$3F,$FF,$C0  ; row 1
        fcb     $00,$00,$03,$C0  ; row 2
        fcb     $00,$3F,$FF,$C0  ; row 3
        fcb     $00,$00,$03,$C0  ; row 4
        fcb     $00,$3F,$FF,$C0  ; row 5
        fcb     $00,$00,$03,$C0  ; row 6
        fcb     $00,$3F,$FC,$0F  ; row 7
