* opacity descriptor (stencil) for scene6_bg_A6EF — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_stencil_punch: 2D mask (height,width, h*w bytes; 11=black,00=keep).
*   cel-local (byte-aligned); a sub-byte-placed cel needs build-side mask shifting.
scene6_bg_A6EF_opacity_stencil:
        fcb     18,2
        fcb     $00,$00  ; row 0
        fcb     $0C,$00  ; row 1
        fcb     $00,$00  ; row 2
        fcb     $0C,$00  ; row 3
        fcb     $00,$00  ; row 4
        fcb     $0C,$00  ; row 5
        fcb     $00,$00  ; row 6
        fcb     $0C,$00  ; row 7
        fcb     $00,$00  ; row 8
        fcb     $FC,$00  ; row 9
        fcb     $F0,$00  ; row 10
        fcb     $FC,$00  ; row 11
        fcb     $F0,$00  ; row 12
        fcb     $FC,$00  ; row 13
        fcb     $F0,$00  ; row 14
        fcb     $FC,$00  ; row 15
        fcb     $F0,$00  ; row 16
        fcb     $FC,$00  ; row 17
