* tests/scripted/scene6_run_anim_gen.s — GENERATED by harness/tools/gen_scene6_placement.py
*   from content/scene6/scene6_placement.txt [animation] run:. DO NOT EDIT the generated file.
*   The §2F single-home player RUN animation table (B0: 12 frames x 3 parts, legs->head->torso,
*   execution-confirmed from the oracle attract). Read by the Stage-B2' driver; include-only.
*   frame block = {fcb dwell, pcnt; per part: fdb cel; fcb col,sub,row}.
run_frames:
        fdb     run_s0,run_s1,run_c0,run_c1,run_c2,run_c3,run_c4,run_c5,run_c6,run_c7,run_e0,run_st
run_frame_count:  fcb 12
run_loop_first:   fcb 2   ; @loop c0
run_loop_last:    fcb 9   ; @loop c7
run_s0:  fcb     11,3
        fdb     player_run_legs_9CAF
        fcb     25,2,143
        fdb     scene6_player_8E9B
        fcb     27,2,116
        fdb     player_run_torso_9E4A
        fcb     26,1,123
run_s1:  fcb     11,3
        fdb     player_run_legs_9CD7
        fcb     24,2,139
        fdb     scene6_player_8E9B
        fcb     28,1,118
        fdb     player_run_torso_9E74
        fcb     26,1,125
run_c0:  fcb     11,3
        fdb     player_run_legs_9B00
        fcb     24,2,141
        fdb     scene6_player_8E9B
        fcb     29,1,119
        fdb     player_run_torso_9D68
        fcb     27,1,126
run_c1:  fcb     11,3
        fdb     player_run_legs_9B6B
        fcb     24,2,141
        fdb     scene6_player_8E9B
        fcb     30,0,119
        fdb     player_run_torso_9D68
        fcb     28,0,126
run_c2:  fcb     11,3
        fdb     player_run_legs_9BE5
        fcb     25,2,149
        fdb     scene6_player_8E9B
        fcb     29,2,119
        fdb     player_run_torso_9DD5
        fcb     28,0,126
run_c3:  fcb     11,3
        fdb     player_run_legs_9C1B
        fcb     24,2,138
        fdb     scene6_player_8E9B
        fcb     27,1,118
        fdb     player_run_torso_9E05
        fcb     26,1,125
run_c4:  fcb     11,3
        fdb     player_run_legs_9B00
        fcb     24,2,141
        fdb     scene6_player_8E9B
        fcb     29,1,119
        fdb     player_run_torso_9D97
        fcb     27,1,126
run_c5:  fcb     11,3
        fdb     player_run_legs_9B6B
        fcb     24,2,141
        fdb     scene6_player_8E9B
        fcb     30,0,119
        fdb     player_run_torso_9D97
        fcb     28,0,126
run_c6:  fcb     11,3
        fdb     player_run_legs_9BE5
        fcb     25,2,149
        fdb     scene6_player_8E9B
        fcb     29,2,119
        fdb     player_run_torso_9DD5
        fcb     28,0,126
run_c7:  fcb     11,3
        fdb     player_run_legs_9C65
        fcb     24,2,138
        fdb     scene6_player_8E9B
        fcb     27,1,118
        fdb     player_run_torso_9E2E
        fcb     26,1,125
run_e0:  fcb     11,3
        fdb     player_run_legs_9D1E
        fcb     24,2,138
        fdb     scene6_player_8E9B
        fcb     26,1,118
        fdb     player_run_torso_9E92
        fcb     24,2,126
run_st:  fcb     21,3
        fdb     scene6_player_899C
        fcb     25,2,138
        fdb     scene6_player_8E9B
        fcb     26,0,116
        fdb     scene6_player_8ACB
        fcb     25,2,124
