* tests/scripted/scene6_fuji_gen.s — GENERATED by harness/tools/gen_scene6_placement.py
*   from content/scene6/scene6_placement.txt [fuji]. DO NOT EDIT. Edit the text-source.
*   The §2F single-home Fuji backdrop placement. Included by scene6_backdrop.s so the
*   shared draw_fuji_cels AND Stage-A's fuji reads share one home. Pure fcb data; no org.
fuji_A9E2:  fcb 26,0,108   ; col, sub, row
fuji_A9B8:  fcb 31,0,100   ; col, sub, row
fuji_A976:  fcb 33,0,92   ; col, sub, row
fuji_A948:  fcb 36,0,81   ; col, sub, row
