* tests/scripted/scene6_arch_gen.s — GENERATED by harness/tools/gen_scene6_placement.py
*   from content/scene6/scene6_placement.txt [animation] arch:. DO NOT EDIT the generated file.
*   The §2F single-home ARCH composite (14 $52-relative cels, traced by spatial region).
*   Positions are the port registration at the halt reference $52=$1B; the driver applies
*   the common scroll delta. Read by the Stage-B2' driver; include-only.
*   Per cel: fdb cel ; fcb col, sub, row0, row1, step  (single => row1=row0, step=1).
arch_count:  fcb 17
arch_tbl:
        fdb     scene6_bg_A707
        fcb     66,0,30,30,1
        fdb     scene6_bg_A857
        fcb     64,1,42,42,1
        fdb     scene6_bg_A82B
        fcb     60,3,48,48,1
        fdb     scene6_bg_A7D1
        fcb     57,1,55,55,1
        fdb     scene6_bg_A763
        fcb     55,2,66,66,1
        fdb     scene6_bg_A865
        fcb     57,1,104,104,1
        fdb     scene6_bg_A877
        fcb     57,1,111,111,1
        fdb     scene6_bg_A87B
        fcb     55,2,153,153,1
        fdb     scene6_bg_A6EF
        fcb     69,2,153,153,1
        fdb     scene6_bg_A6A6
        fcb     59,0,159,159,1
        fdb     scene6_bg_A703
        fcb     69,2,66,102,2
        fdb     scene6_bg_A684
        fcb     66,0,66,170,2
        fdb     scene6_bg_A85F
        fcb     57,1,84,102,2
        fdb     scene6_bg_A68A
        fcb     57,1,111,151,2
        fdb     scene6_bg_A6C0
        fcb     60,3,165,165,1
        fdb     scene6_bg_A6D4
        fcb     64,1,171,171,1
        fdb     scene6_bg_archfill1
        fcb     64,3,165,165,1
