* tests/scripted/scene6_post_masks_gen.s — GENERATED by the B2' post generator.
*   The wall-top post pre-baked as AND/OR RMW mask columns at each sub-byte phase.
*   Shape derived from the gated tableau's own masks (posts 2 and 3): 2 px white at
*   x,x+1 then black at x+2..x+5. Pitch 85 px (Jay: use the 2nd->3rd spacing, 183->268;
*   post 1 at 103 is off-series and is NOT the reference).
*   Layout per phase: 3 AND bytes then 3 OR bytes, applied at byte (x>>2)+0..2.
post_masks:
        fcb     $00,$0F,$FF,$F0,$00,$00   ; phase 0
        fcb     $C0,$03,$FF,$3C,$00,$00   ; phase 1
        fcb     $F0,$00,$FF,$0F,$00,$00   ; phase 2
        fcb     $FC,$00,$3F,$03,$C0,$00   ; phase 3
