* tests/scripted/scene6_placement_gen.s — GENERATED by harness/tools/gen_scene6_placement.py
*   from content/scene6/scene6_placement.txt. DO NOT EDIT. Edit the text-source, re-run the codegen.
*   The single-home (§2F) scene-6 placement table the build reads. include-only; no org.
* --- registry: reg_<id> = fcb w, h, start_col (start_col promoted from the cel comment) ---
reg_AA7D:  fcb 11,29,42   ; w, h, start_col
reg_AB4A:  fcb 20,4,0   ; w, h, start_col
reg_AB7C:  fcb 4,8,70   ; w, h, start_col
reg_AB94:  fcb 3,4,70   ; w, h, start_col
reg_AA23:  fcb 1,12,79   ; w, h, start_col
reg_AA31:  fcb 2,12,79   ; w, h, start_col
reg_A9E2:  fcb 27,3,0   ; w, h, start_col
reg_A9B8:  fcb 18,4,0   ; w, h, start_col
reg_A976:  fcb 14,8,0   ; w, h, start_col
reg_A948:  fcb 7,11,0   ; w, h, start_col
reg_A3C5:  fcb 4,17,0   ; w, h, start_col
reg_A3E9:  fcb 6,8,0   ; w, h, start_col
reg_A425:  fcb 6,17,0   ; w, h, start_col
reg_A40B:  fcb 4,8,0   ; w, h, start_col
reg_A4A4:  fcb 4,22,70   ; w, h, start_col
reg_A45A:  fcb 6,24,0   ; w, h, start_col
reg_A4F2:  fcb 7,21,0   ; w, h, start_col
reg_A4D2:  fcb 9,6,0   ; w, h, start_col
reg_A572:  fcb 7,22,0   ; w, h, start_col
reg_A548:  fcb 7,10,0   ; w, h, start_col
reg_A5DC:  fcb 6,36,0   ; w, h, start_col
reg_A5CC:  fcb 3,7,0   ; w, h, start_col
reg_899C:  fcb 3,24,0   ; w, h, start_col
reg_8ACB:  fcb 3,14,0   ; w, h, start_col
reg_8E9B:  fcb 2,8,0   ; w, h, start_col
* --- placement: plc_<id> = fcb col, sub, row (byte-col, sub-byte shift 0..3, row) ---
plc_AB4A:  fcb 5,0,112   ; AB4A: col, sub, row
plc_AA7D:  fcb 15,0,152   ; AA7D: col, sub, row
plc_AB7C:  fcb 22,0,104   ; AB7C: col, sub, row
plc_AB94:  fcb 22,0,112   ; AB94: col, sub, row
plc_AA31_0:  fcb 24,0,100   ; AA31: col, sub, row
plc_AA31_1:  fcb 45,0,100   ; AA31: col, sub, row
plc_AA31_2:  fcb 66,0,100   ; AA31: col, sub, row
plc_AA23_0:  fcb 25,0,100   ; AA23: col, sub, row
plc_AA23_1:  fcb 46,0,100   ; AA23: col, sub, row
plc_AA23_2:  fcb 67,0,100   ; AA23: col, sub, row
* --- startpose: plc_start_<cel> = fcb col,sub,row (DERIVED from [animation] climb_crawl f0) ---
plc_start_A3E9:  fcb 21,3,158   ; crawl-start (= climb_crawl f0)
plc_start_A3C5:  fcb 22,2,141   ; crawl-start (= climb_crawl f0)
