* tests/scripted/scene6_arch_opacity_scroll_gen.s — GENERATED by gen_arch_opacity_scroll.py
*   per-SUB opacity STENCILS (opaque index-0 black) for the arch cels + arch_stencil_tbl.
*   Four pre-shifted stencils per cel (sub 0..3); draw_arch selects by the runtime sub.
*   Same pixel-precise masks as the approved static arch. DO NOT EDIT. include-only; no org.

aops_A707_s0:  ; stencil pre-shifted right by sub=0px
        fcb     18,9
        fcb     $00,$00,$00,$03,$C0,$00,$00,$F0,$00  ; row 0
        fcb     $00,$00,$00,$00,$FF,$FF,$FF,$F0,$00  ; row 1
        fcb     $00,$00,$00,$00,$00,$00,$00,$F0,$00  ; row 2
        fcb     $00,$00,$00,$00,$FF,$FF,$FF,$F0,$00  ; row 3
        fcb     $00,$00,$00,$00,$00,$00,$00,$F0,$00  ; row 4
        fcb     $00,$00,$00,$00,$FF,$FF,$FF,$F0,$00  ; row 5
        fcb     $00,$00,$00,$00,$00,$00,$00,$F0,$00  ; row 6
        fcb     $00,$00,$00,$00,$FF,$FF,$FF,$F0,$00  ; row 7
        fcb     $00,$00,$00,$00,$00,$00,$00,$F0,$00  ; row 8
        fcb     $00,$00,$00,$00,$FF,$FF,$FF,$F0,$00  ; row 9
        fcb     $00,$00,$00,$00,$00,$00,$00,$F0,$00  ; row 10
        fcb     $00,$00,$00,$3F,$FF,$FF,$FF,$F0,$00  ; row 11
        fcb     $00,$00,$03,$FF,$FF,$FF,$FF,$00,$00  ; row 12
        fcb     $00,$00,$0F,$FF,$FF,$FF,$F0,$00,$00  ; row 13
        fcb     $00,$00,$FF,$FF,$FF,$FF,$00,$00,$00  ; row 14
        fcb     $00,$03,$FF,$FF,$FF,$F0,$00,$00,$00  ; row 15
        fcb     $00,$3F,$FF,$FF,$FF,$00,$00,$00,$00  ; row 16
        fcb     $03,$FF,$FF,$FF,$F0,$00,$00,$00,$00  ; row 17
aops_A707_s1:  ; stencil pre-shifted right by sub=1px
        fcb     18,10
        fcb     $00,$00,$00,$00,$F0,$00,$00,$3C,$00,$00  ; row 0
        fcb     $00,$00,$00,$00,$3F,$FF,$FF,$FC,$00,$00  ; row 1
        fcb     $00,$00,$00,$00,$00,$00,$00,$3C,$00,$00  ; row 2
        fcb     $00,$00,$00,$00,$3F,$FF,$FF,$FC,$00,$00  ; row 3
        fcb     $00,$00,$00,$00,$00,$00,$00,$3C,$00,$00  ; row 4
        fcb     $00,$00,$00,$00,$3F,$FF,$FF,$FC,$00,$00  ; row 5
        fcb     $00,$00,$00,$00,$00,$00,$00,$3C,$00,$00  ; row 6
        fcb     $00,$00,$00,$00,$3F,$FF,$FF,$FC,$00,$00  ; row 7
        fcb     $00,$00,$00,$00,$00,$00,$00,$3C,$00,$00  ; row 8
        fcb     $00,$00,$00,$00,$3F,$FF,$FF,$FC,$00,$00  ; row 9
        fcb     $00,$00,$00,$00,$00,$00,$00,$3C,$00,$00  ; row 10
        fcb     $00,$00,$00,$0F,$FF,$FF,$FF,$FC,$00,$00  ; row 11
        fcb     $00,$00,$00,$FF,$FF,$FF,$FF,$C0,$00,$00  ; row 12
        fcb     $00,$00,$03,$FF,$FF,$FF,$FC,$00,$00,$00  ; row 13
        fcb     $00,$00,$3F,$FF,$FF,$FF,$C0,$00,$00,$00  ; row 14
        fcb     $00,$00,$FF,$FF,$FF,$FC,$00,$00,$00,$00  ; row 15
        fcb     $00,$0F,$FF,$FF,$FF,$C0,$00,$00,$00,$00  ; row 16
        fcb     $00,$FF,$FF,$FF,$FC,$00,$00,$00,$00,$00  ; row 17
aops_A707_s2:  ; stencil pre-shifted right by sub=2px
        fcb     18,10
        fcb     $00,$00,$00,$00,$3C,$00,$00,$0F,$00,$00  ; row 0
        fcb     $00,$00,$00,$00,$0F,$FF,$FF,$FF,$00,$00  ; row 1
        fcb     $00,$00,$00,$00,$00,$00,$00,$0F,$00,$00  ; row 2
        fcb     $00,$00,$00,$00,$0F,$FF,$FF,$FF,$00,$00  ; row 3
        fcb     $00,$00,$00,$00,$00,$00,$00,$0F,$00,$00  ; row 4
        fcb     $00,$00,$00,$00,$0F,$FF,$FF,$FF,$00,$00  ; row 5
        fcb     $00,$00,$00,$00,$00,$00,$00,$0F,$00,$00  ; row 6
        fcb     $00,$00,$00,$00,$0F,$FF,$FF,$FF,$00,$00  ; row 7
        fcb     $00,$00,$00,$00,$00,$00,$00,$0F,$00,$00  ; row 8
        fcb     $00,$00,$00,$00,$0F,$FF,$FF,$FF,$00,$00  ; row 9
        fcb     $00,$00,$00,$00,$00,$00,$00,$0F,$00,$00  ; row 10
        fcb     $00,$00,$00,$03,$FF,$FF,$FF,$FF,$00,$00  ; row 11
        fcb     $00,$00,$00,$3F,$FF,$FF,$FF,$F0,$00,$00  ; row 12
        fcb     $00,$00,$00,$FF,$FF,$FF,$FF,$00,$00,$00  ; row 13
        fcb     $00,$00,$0F,$FF,$FF,$FF,$F0,$00,$00,$00  ; row 14
        fcb     $00,$00,$3F,$FF,$FF,$FF,$00,$00,$00,$00  ; row 15
        fcb     $00,$03,$FF,$FF,$FF,$F0,$00,$00,$00,$00  ; row 16
        fcb     $00,$3F,$FF,$FF,$FF,$00,$00,$00,$00,$00  ; row 17
aops_A707_s3:  ; stencil pre-shifted right by sub=3px
        fcb     18,10
        fcb     $00,$00,$00,$00,$0F,$00,$00,$03,$C0,$00  ; row 0
        fcb     $00,$00,$00,$00,$03,$FF,$FF,$FF,$C0,$00  ; row 1
        fcb     $00,$00,$00,$00,$00,$00,$00,$03,$C0,$00  ; row 2
        fcb     $00,$00,$00,$00,$03,$FF,$FF,$FF,$C0,$00  ; row 3
        fcb     $00,$00,$00,$00,$00,$00,$00,$03,$C0,$00  ; row 4
        fcb     $00,$00,$00,$00,$03,$FF,$FF,$FF,$C0,$00  ; row 5
        fcb     $00,$00,$00,$00,$00,$00,$00,$03,$C0,$00  ; row 6
        fcb     $00,$00,$00,$00,$03,$FF,$FF,$FF,$C0,$00  ; row 7
        fcb     $00,$00,$00,$00,$00,$00,$00,$03,$C0,$00  ; row 8
        fcb     $00,$00,$00,$00,$03,$FF,$FF,$FF,$C0,$00  ; row 9
        fcb     $00,$00,$00,$00,$00,$00,$00,$03,$C0,$00  ; row 10
        fcb     $00,$00,$00,$00,$FF,$FF,$FF,$FF,$C0,$00  ; row 11
        fcb     $00,$00,$00,$0F,$FF,$FF,$FF,$FC,$00,$00  ; row 12
        fcb     $00,$00,$00,$3F,$FF,$FF,$FF,$C0,$00,$00  ; row 13
        fcb     $00,$00,$03,$FF,$FF,$FF,$FC,$00,$00,$00  ; row 14
        fcb     $00,$00,$0F,$FF,$FF,$FF,$C0,$00,$00,$00  ; row 15
        fcb     $00,$00,$FF,$FF,$FF,$FC,$00,$00,$00,$00  ; row 16
        fcb     $00,$0F,$FF,$FF,$FF,$C0,$00,$00,$00,$00  ; row 17
aops_A82B_s0:  ; stencil pre-shifted right by sub=0px
        fcb     7,11
        fcb     $00,$00,$00,$00,$00,$03,$F0,$00,$00,$00,$00  ; row 0
        fcb     $00,$00,$00,$00,$00,$3F,$03,$FF,$FC,$00,$00  ; row 1
        fcb     $00,$00,$00,$00,$00,$F0,$00,$00,$00,$00,$00  ; row 2
        fcb     $00,$00,$00,$00,$0F,$C0,$03,$FF,$FC,$00,$00  ; row 3
        fcb     $00,$00,$00,$00,$3F,$C0,$00,$00,$00,$00,$00  ; row 4
        fcb     $00,$00,$00,$03,$FF,$C0,$03,$FF,$FC,$00,$00  ; row 5
        fcb     $00,$00,$00,$3F,$FF,$C0,$00,$00,$00,$00,$00  ; row 6
aops_A82B_s1:  ; stencil pre-shifted right by sub=1px
        fcb     7,12
        fcb     $00,$00,$00,$00,$00,$00,$FC,$00,$00,$00,$00,$00  ; row 0
        fcb     $00,$00,$00,$00,$00,$0F,$C0,$FF,$FF,$00,$00,$00  ; row 1
        fcb     $00,$00,$00,$00,$00,$3C,$00,$00,$00,$00,$00,$00  ; row 2
        fcb     $00,$00,$00,$00,$03,$F0,$00,$FF,$FF,$00,$00,$00  ; row 3
        fcb     $00,$00,$00,$00,$0F,$F0,$00,$00,$00,$00,$00,$00  ; row 4
        fcb     $00,$00,$00,$00,$FF,$F0,$00,$FF,$FF,$00,$00,$00  ; row 5
        fcb     $00,$00,$00,$0F,$FF,$F0,$00,$00,$00,$00,$00,$00  ; row 6
aops_A82B_s2:  ; stencil pre-shifted right by sub=2px
        fcb     7,12
        fcb     $00,$00,$00,$00,$00,$00,$3F,$00,$00,$00,$00,$00  ; row 0
        fcb     $00,$00,$00,$00,$00,$03,$F0,$3F,$FF,$C0,$00,$00  ; row 1
        fcb     $00,$00,$00,$00,$00,$0F,$00,$00,$00,$00,$00,$00  ; row 2
        fcb     $00,$00,$00,$00,$00,$FC,$00,$3F,$FF,$C0,$00,$00  ; row 3
        fcb     $00,$00,$00,$00,$03,$FC,$00,$00,$00,$00,$00,$00  ; row 4
        fcb     $00,$00,$00,$00,$3F,$FC,$00,$3F,$FF,$C0,$00,$00  ; row 5
        fcb     $00,$00,$00,$03,$FF,$FC,$00,$00,$00,$00,$00,$00  ; row 6
aops_A82B_s3:  ; stencil pre-shifted right by sub=3px
        fcb     7,12
        fcb     $00,$00,$00,$00,$00,$00,$0F,$C0,$00,$00,$00,$00  ; row 0
        fcb     $00,$00,$00,$00,$00,$00,$FC,$0F,$FF,$F0,$00,$00  ; row 1
        fcb     $00,$00,$00,$00,$00,$03,$C0,$00,$00,$00,$00,$00  ; row 2
        fcb     $00,$00,$00,$00,$00,$3F,$00,$0F,$FF,$F0,$00,$00  ; row 3
        fcb     $00,$00,$00,$00,$00,$FF,$00,$00,$00,$00,$00,$00  ; row 4
        fcb     $00,$00,$00,$00,$0F,$FF,$00,$0F,$FF,$F0,$00,$00  ; row 5
        fcb     $00,$00,$00,$00,$FF,$FF,$00,$00,$00,$00,$00,$00  ; row 6
aops_A7D1_s0:  ; stencil pre-shifted right by sub=0px
        fcb     11,14
        fcb     $00,$00,$00,$00,$00,$00,$0F,$FF,$FC,$00,$3F,$FF,$FF,$FC  ; row 0
        fcb     $00,$00,$00,$00,$00,$00,$FF,$FF,$FC,$00,$3F,$00,$00,$3C  ; row 1
        fcb     $00,$00,$00,$00,$00,$03,$FF,$FF,$FC,$00,$00,$03,$FF,$FC  ; row 2
        fcb     $00,$00,$00,$00,$00,$3F,$FF,$FF,$FC,$00,$00,$00,$00,$3C  ; row 3
        fcb     $00,$00,$00,$00,$00,$FF,$FF,$FF,$C0,$00,$00,$03,$FF,$FC  ; row 4
        fcb     $00,$00,$00,$00,$0F,$FF,$FF,$FC,$00,$00,$00,$00,$00,$3C  ; row 5
        fcb     $00,$00,$00,$00,$FF,$FF,$FF,$C0,$00,$00,$00,$03,$FF,$FC  ; row 6
        fcb     $00,$00,$00,$03,$FF,$FF,$FC,$00,$00,$00,$00,$00,$00,$3C  ; row 7
        fcb     $00,$00,$00,$3F,$FF,$FF,$C0,$00,$00,$00,$00,$3F,$FF,$FC  ; row 8
        fcb     $00,$00,$00,$FF,$FF,$FC,$00,$00,$00,$00,$03,$FF,$FF,$C0  ; row 9
        fcb     $00,$00,$0F,$FF,$FF,$C0,$00,$00,$00,$00,$3F,$FF,$FC,$00  ; row 10
aops_A7D1_s1:  ; stencil pre-shifted right by sub=1px
        fcb     11,15
        fcb     $00,$00,$00,$00,$00,$00,$03,$FF,$FF,$00,$0F,$FF,$FF,$FF,$00  ; row 0
        fcb     $00,$00,$00,$00,$00,$00,$3F,$FF,$FF,$00,$0F,$C0,$00,$0F,$00  ; row 1
        fcb     $00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$00,$00,$00,$FF,$FF,$00  ; row 2
        fcb     $00,$00,$00,$00,$00,$0F,$FF,$FF,$FF,$00,$00,$00,$00,$0F,$00  ; row 3
        fcb     $00,$00,$00,$00,$00,$3F,$FF,$FF,$F0,$00,$00,$00,$FF,$FF,$00  ; row 4
        fcb     $00,$00,$00,$00,$03,$FF,$FF,$FF,$00,$00,$00,$00,$00,$0F,$00  ; row 5
        fcb     $00,$00,$00,$00,$3F,$FF,$FF,$F0,$00,$00,$00,$00,$FF,$FF,$00  ; row 6
        fcb     $00,$00,$00,$00,$FF,$FF,$FF,$00,$00,$00,$00,$00,$00,$0F,$00  ; row 7
        fcb     $00,$00,$00,$0F,$FF,$FF,$F0,$00,$00,$00,$00,$0F,$FF,$FF,$00  ; row 8
        fcb     $00,$00,$00,$3F,$FF,$FF,$00,$00,$00,$00,$00,$FF,$FF,$F0,$00  ; row 9
        fcb     $00,$00,$03,$FF,$FF,$F0,$00,$00,$00,$00,$0F,$FF,$FF,$00,$00  ; row 10
aops_A7D1_s2:  ; stencil pre-shifted right by sub=2px
        fcb     11,15
        fcb     $00,$00,$00,$00,$00,$00,$00,$FF,$FF,$C0,$03,$FF,$FF,$FF,$C0  ; row 0
        fcb     $00,$00,$00,$00,$00,$00,$0F,$FF,$FF,$C0,$03,$F0,$00,$03,$C0  ; row 1
        fcb     $00,$00,$00,$00,$00,$00,$3F,$FF,$FF,$C0,$00,$00,$3F,$FF,$C0  ; row 2
        fcb     $00,$00,$00,$00,$00,$03,$FF,$FF,$FF,$C0,$00,$00,$00,$03,$C0  ; row 3
        fcb     $00,$00,$00,$00,$00,$0F,$FF,$FF,$FC,$00,$00,$00,$3F,$FF,$C0  ; row 4
        fcb     $00,$00,$00,$00,$00,$FF,$FF,$FF,$C0,$00,$00,$00,$00,$03,$C0  ; row 5
        fcb     $00,$00,$00,$00,$0F,$FF,$FF,$FC,$00,$00,$00,$00,$3F,$FF,$C0  ; row 6
        fcb     $00,$00,$00,$00,$3F,$FF,$FF,$C0,$00,$00,$00,$00,$00,$03,$C0  ; row 7
        fcb     $00,$00,$00,$03,$FF,$FF,$FC,$00,$00,$00,$00,$03,$FF,$FF,$C0  ; row 8
        fcb     $00,$00,$00,$0F,$FF,$FF,$C0,$00,$00,$00,$00,$3F,$FF,$FC,$00  ; row 9
        fcb     $00,$00,$00,$FF,$FF,$FC,$00,$00,$00,$00,$03,$FF,$FF,$C0,$00  ; row 10
aops_A7D1_s3:  ; stencil pre-shifted right by sub=3px
        fcb     11,15
        fcb     $00,$00,$00,$00,$00,$00,$00,$3F,$FF,$F0,$00,$FF,$FF,$FF,$F0  ; row 0
        fcb     $00,$00,$00,$00,$00,$00,$03,$FF,$FF,$F0,$00,$FC,$00,$00,$F0  ; row 1
        fcb     $00,$00,$00,$00,$00,$00,$0F,$FF,$FF,$F0,$00,$00,$0F,$FF,$F0  ; row 2
        fcb     $00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$F0,$00,$00,$00,$00,$F0  ; row 3
        fcb     $00,$00,$00,$00,$00,$03,$FF,$FF,$FF,$00,$00,$00,$0F,$FF,$F0  ; row 4
        fcb     $00,$00,$00,$00,$00,$3F,$FF,$FF,$F0,$00,$00,$00,$00,$00,$F0  ; row 5
        fcb     $00,$00,$00,$00,$03,$FF,$FF,$FF,$00,$00,$00,$00,$0F,$FF,$F0  ; row 6
        fcb     $00,$00,$00,$00,$0F,$FF,$FF,$F0,$00,$00,$00,$00,$00,$00,$F0  ; row 7
        fcb     $00,$00,$00,$00,$FF,$FF,$FF,$00,$00,$00,$00,$00,$FF,$FF,$F0  ; row 8
        fcb     $00,$00,$00,$03,$FF,$FF,$F0,$00,$00,$00,$00,$0F,$FF,$FF,$00  ; row 9
        fcb     $00,$00,$00,$3F,$FF,$FF,$00,$00,$00,$00,$00,$FF,$FF,$F0,$00  ; row 10
aops_A763_s0:  ; stencil pre-shifted right by sub=0px
        fcb     18,11
        fcb     $00,$00,$00,$00,$FF,$FF,$FF,$00,$00,$00,$00  ; row 0
        fcb     $00,$00,$00,$0F,$FF,$FF,$F0,$00,$00,$00,$00  ; row 1
        fcb     $00,$00,$00,$FF,$FF,$FF,$00,$00,$00,$00,$F0  ; row 2
        fcb     $00,$00,$03,$FF,$FF,$F0,$00,$00,$00,$0F,$F0  ; row 3
        fcb     $00,$00,$3F,$FF,$FF,$00,$00,$00,$00,$FF,$F0  ; row 4
        fcb     $00,$00,$F0,$00,$0F,$00,$00,$00,$0F,$FF,$F0  ; row 5
        fcb     $00,$0F,$00,$FF,$FF,$00,$00,$00,$FF,$FF,$F0  ; row 6
        fcb     $00,$3F,$00,$00,$F0,$00,$00,$0F,$FF,$FF,$00  ; row 7
        fcb     $03,$FF,$00,$FF,$00,$00,$00,$FF,$FF,$F0,$00  ; row 8
        fcb     $3F,$FF,$00,$F0,$00,$00,$3F,$FF,$FF,$00,$00  ; row 9
        fcb     $FF,$FF,$00,$00,$00,$03,$FF,$FF,$F0,$00,$00  ; row 10
        fcb     $00,$00,$00,$00,$00,$3F,$FF,$FF,$00,$00,$00  ; row 11
        fcb     $00,$00,$00,$00,$03,$FF,$FF,$00,$00,$00,$00  ; row 12
        fcb     $00,$00,$00,$00,$3F,$FF,$F0,$00,$00,$00,$00  ; row 13
        fcb     $00,$00,$00,$03,$FF,$FF,$00,$00,$00,$00,$00  ; row 14
        fcb     $00,$00,$00,$FF,$FF,$F0,$00,$00,$00,$00,$00  ; row 15
        fcb     $00,$00,$00,$00,$0F,$00,$00,$00,$00,$00,$00  ; row 16
        fcb     $00,$00,$00,$FF,$FF,$00,$00,$00,$00,$00,$00  ; row 17
aops_A763_s1:  ; stencil pre-shifted right by sub=1px
        fcb     18,12
        fcb     $00,$00,$00,$00,$3F,$FF,$FF,$C0,$00,$00,$00,$00  ; row 0
        fcb     $00,$00,$00,$03,$FF,$FF,$FC,$00,$00,$00,$00,$00  ; row 1
        fcb     $00,$00,$00,$3F,$FF,$FF,$C0,$00,$00,$00,$3C,$00  ; row 2
        fcb     $00,$00,$00,$FF,$FF,$FC,$00,$00,$00,$03,$FC,$00  ; row 3
        fcb     $00,$00,$0F,$FF,$FF,$C0,$00,$00,$00,$3F,$FC,$00  ; row 4
        fcb     $00,$00,$3C,$00,$03,$C0,$00,$00,$03,$FF,$FC,$00  ; row 5
        fcb     $00,$03,$C0,$3F,$FF,$C0,$00,$00,$3F,$FF,$FC,$00  ; row 6
        fcb     $00,$0F,$C0,$00,$3C,$00,$00,$03,$FF,$FF,$C0,$00  ; row 7
        fcb     $00,$FF,$C0,$3F,$C0,$00,$00,$3F,$FF,$FC,$00,$00  ; row 8
        fcb     $0F,$FF,$C0,$3C,$00,$00,$0F,$FF,$FF,$C0,$00,$00  ; row 9
        fcb     $3F,$FF,$C0,$00,$00,$00,$FF,$FF,$FC,$00,$00,$00  ; row 10
        fcb     $00,$00,$00,$00,$00,$0F,$FF,$FF,$C0,$00,$00,$00  ; row 11
        fcb     $00,$00,$00,$00,$00,$FF,$FF,$C0,$00,$00,$00,$00  ; row 12
        fcb     $00,$00,$00,$00,$0F,$FF,$FC,$00,$00,$00,$00,$00  ; row 13
        fcb     $00,$00,$00,$00,$FF,$FF,$C0,$00,$00,$00,$00,$00  ; row 14
        fcb     $00,$00,$00,$3F,$FF,$FC,$00,$00,$00,$00,$00,$00  ; row 15
        fcb     $00,$00,$00,$00,$03,$C0,$00,$00,$00,$00,$00,$00  ; row 16
        fcb     $00,$00,$00,$3F,$FF,$C0,$00,$00,$00,$00,$00,$00  ; row 17
aops_A763_s2:  ; stencil pre-shifted right by sub=2px
        fcb     18,12
        fcb     $00,$00,$00,$00,$0F,$FF,$FF,$F0,$00,$00,$00,$00  ; row 0
        fcb     $00,$00,$00,$00,$FF,$FF,$FF,$00,$00,$00,$00,$00  ; row 1
        fcb     $00,$00,$00,$0F,$FF,$FF,$F0,$00,$00,$00,$0F,$00  ; row 2
        fcb     $00,$00,$00,$3F,$FF,$FF,$00,$00,$00,$00,$FF,$00  ; row 3
        fcb     $00,$00,$03,$FF,$FF,$F0,$00,$00,$00,$0F,$FF,$00  ; row 4
        fcb     $00,$00,$0F,$00,$00,$F0,$00,$00,$00,$FF,$FF,$00  ; row 5
        fcb     $00,$00,$F0,$0F,$FF,$F0,$00,$00,$0F,$FF,$FF,$00  ; row 6
        fcb     $00,$03,$F0,$00,$0F,$00,$00,$00,$FF,$FF,$F0,$00  ; row 7
        fcb     $00,$3F,$F0,$0F,$F0,$00,$00,$0F,$FF,$FF,$00,$00  ; row 8
        fcb     $03,$FF,$F0,$0F,$00,$00,$03,$FF,$FF,$F0,$00,$00  ; row 9
        fcb     $0F,$FF,$F0,$00,$00,$00,$3F,$FF,$FF,$00,$00,$00  ; row 10
        fcb     $00,$00,$00,$00,$00,$03,$FF,$FF,$F0,$00,$00,$00  ; row 11
        fcb     $00,$00,$00,$00,$00,$3F,$FF,$F0,$00,$00,$00,$00  ; row 12
        fcb     $00,$00,$00,$00,$03,$FF,$FF,$00,$00,$00,$00,$00  ; row 13
        fcb     $00,$00,$00,$00,$3F,$FF,$F0,$00,$00,$00,$00,$00  ; row 14
        fcb     $00,$00,$00,$0F,$FF,$FF,$00,$00,$00,$00,$00,$00  ; row 15
        fcb     $00,$00,$00,$00,$00,$F0,$00,$00,$00,$00,$00,$00  ; row 16
        fcb     $00,$00,$00,$0F,$FF,$F0,$00,$00,$00,$00,$00,$00  ; row 17
aops_A763_s3:  ; stencil pre-shifted right by sub=3px
        fcb     18,12
        fcb     $00,$00,$00,$00,$03,$FF,$FF,$FC,$00,$00,$00,$00  ; row 0
        fcb     $00,$00,$00,$00,$3F,$FF,$FF,$C0,$00,$00,$00,$00  ; row 1
        fcb     $00,$00,$00,$03,$FF,$FF,$FC,$00,$00,$00,$03,$C0  ; row 2
        fcb     $00,$00,$00,$0F,$FF,$FF,$C0,$00,$00,$00,$3F,$C0  ; row 3
        fcb     $00,$00,$00,$FF,$FF,$FC,$00,$00,$00,$03,$FF,$C0  ; row 4
        fcb     $00,$00,$03,$C0,$00,$3C,$00,$00,$00,$3F,$FF,$C0  ; row 5
        fcb     $00,$00,$3C,$03,$FF,$FC,$00,$00,$03,$FF,$FF,$C0  ; row 6
        fcb     $00,$00,$FC,$00,$03,$C0,$00,$00,$3F,$FF,$FC,$00  ; row 7
        fcb     $00,$0F,$FC,$03,$FC,$00,$00,$03,$FF,$FF,$C0,$00  ; row 8
        fcb     $00,$FF,$FC,$03,$C0,$00,$00,$FF,$FF,$FC,$00,$00  ; row 9
        fcb     $03,$FF,$FC,$00,$00,$00,$0F,$FF,$FF,$C0,$00,$00  ; row 10
        fcb     $00,$00,$00,$00,$00,$00,$FF,$FF,$FC,$00,$00,$00  ; row 11
        fcb     $00,$00,$00,$00,$00,$0F,$FF,$FC,$00,$00,$00,$00  ; row 12
        fcb     $00,$00,$00,$00,$00,$FF,$FF,$C0,$00,$00,$00,$00  ; row 13
        fcb     $00,$00,$00,$00,$0F,$FF,$FC,$00,$00,$00,$00,$00  ; row 14
        fcb     $00,$00,$00,$03,$FF,$FF,$C0,$00,$00,$00,$00,$00  ; row 15
        fcb     $00,$00,$00,$00,$00,$3C,$00,$00,$00,$00,$00,$00  ; row 16
        fcb     $00,$00,$00,$03,$FF,$FC,$00,$00,$00,$00,$00,$00  ; row 17
aops_A865_s0:  ; stencil pre-shifted right by sub=0px
        fcb     8,4
        fcb     $00,$00,$03,$C0  ; row 0
        fcb     $00,$3F,$FF,$C0  ; row 1
        fcb     $00,$00,$03,$C0  ; row 2
        fcb     $00,$3F,$FF,$C0  ; row 3
        fcb     $00,$00,$03,$C0  ; row 4
        fcb     $00,$3F,$FF,$C0  ; row 5
        fcb     $00,$00,$03,$C0  ; row 6
        fcb     $00,$3F,$FC,$0F  ; row 7
aops_A865_s1:  ; stencil pre-shifted right by sub=1px
        fcb     8,5
        fcb     $00,$00,$00,$F0,$00  ; row 0
        fcb     $00,$0F,$FF,$F0,$00  ; row 1
        fcb     $00,$00,$00,$F0,$00  ; row 2
        fcb     $00,$0F,$FF,$F0,$00  ; row 3
        fcb     $00,$00,$00,$F0,$00  ; row 4
        fcb     $00,$0F,$FF,$F0,$00  ; row 5
        fcb     $00,$00,$00,$F0,$00  ; row 6
        fcb     $00,$0F,$FF,$03,$C0  ; row 7
aops_A865_s2:  ; stencil pre-shifted right by sub=2px
        fcb     8,5
        fcb     $00,$00,$00,$3C,$00  ; row 0
        fcb     $00,$03,$FF,$FC,$00  ; row 1
        fcb     $00,$00,$00,$3C,$00  ; row 2
        fcb     $00,$03,$FF,$FC,$00  ; row 3
        fcb     $00,$00,$00,$3C,$00  ; row 4
        fcb     $00,$03,$FF,$FC,$00  ; row 5
        fcb     $00,$00,$00,$3C,$00  ; row 6
        fcb     $00,$03,$FF,$C0,$F0  ; row 7
aops_A865_s3:  ; stencil pre-shifted right by sub=3px
        fcb     8,5
        fcb     $00,$00,$00,$0F,$00  ; row 0
        fcb     $00,$00,$FF,$FF,$00  ; row 1
        fcb     $00,$00,$00,$0F,$00  ; row 2
        fcb     $00,$00,$FF,$FF,$00  ; row 3
        fcb     $00,$00,$00,$0F,$00  ; row 4
        fcb     $00,$00,$FF,$FF,$00  ; row 5
        fcb     $00,$00,$00,$0F,$00  ; row 6
        fcb     $00,$00,$FF,$F0,$3C  ; row 7
aops_A877_s0:  ; stencil pre-shifted right by sub=0px
        fcb     1,4
        fcb     $00,$00,$00,$C0  ; row 0
aops_A877_s1:  ; stencil pre-shifted right by sub=1px
        fcb     1,5
        fcb     $00,$00,$00,$30,$00  ; row 0
aops_A877_s2:  ; stencil pre-shifted right by sub=2px
        fcb     1,5
        fcb     $00,$00,$00,$0C,$00  ; row 0
aops_A877_s3:  ; stencil pre-shifted right by sub=3px
        fcb     1,5
        fcb     $00,$00,$00,$03,$00  ; row 0
aops_A87B_s0:  ; stencil pre-shifted right by sub=0px
        fcb     6,7
        fcb     $00,$00,$00,$FF,$FF,$00,$00  ; row 0
        fcb     $03,$FF,$00,$00,$0F,$C0,$00  ; row 1
        fcb     $00,$3F,$00,$FF,$FF,$00,$00  ; row 2
        fcb     $00,$00,$F0,$00,$0F,$FC,$00  ; row 3
        fcb     $00,$00,$3F,$FF,$FF,$FF,$00  ; row 4
        fcb     $00,$00,$00,$FF,$FF,$FF,$FC  ; row 5
aops_A87B_s1:  ; stencil pre-shifted right by sub=1px
        fcb     6,8
        fcb     $00,$00,$00,$3F,$FF,$C0,$00,$00  ; row 0
        fcb     $00,$FF,$C0,$00,$03,$F0,$00,$00  ; row 1
        fcb     $00,$0F,$C0,$3F,$FF,$C0,$00,$00  ; row 2
        fcb     $00,$00,$3C,$00,$03,$FF,$00,$00  ; row 3
        fcb     $00,$00,$0F,$FF,$FF,$FF,$C0,$00  ; row 4
        fcb     $00,$00,$00,$3F,$FF,$FF,$FF,$00  ; row 5
aops_A87B_s2:  ; stencil pre-shifted right by sub=2px
        fcb     6,8
        fcb     $00,$00,$00,$0F,$FF,$F0,$00,$00  ; row 0
        fcb     $00,$3F,$F0,$00,$00,$FC,$00,$00  ; row 1
        fcb     $00,$03,$F0,$0F,$FF,$F0,$00,$00  ; row 2
        fcb     $00,$00,$0F,$00,$00,$FF,$C0,$00  ; row 3
        fcb     $00,$00,$03,$FF,$FF,$FF,$F0,$00  ; row 4
        fcb     $00,$00,$00,$0F,$FF,$FF,$FF,$C0  ; row 5
aops_A87B_s3:  ; stencil pre-shifted right by sub=3px
        fcb     6,8
        fcb     $00,$00,$00,$03,$FF,$FC,$00,$00  ; row 0
        fcb     $00,$0F,$FC,$00,$00,$3F,$00,$00  ; row 1
        fcb     $00,$00,$FC,$03,$FF,$FC,$00,$00  ; row 2
        fcb     $00,$00,$03,$C0,$00,$3F,$F0,$00  ; row 3
        fcb     $00,$00,$00,$FF,$FF,$FF,$FC,$00  ; row 4
        fcb     $00,$00,$00,$03,$FF,$FF,$FF,$F0  ; row 5
aops_A6EF_s0:  ; stencil pre-shifted right by sub=0px
        fcb     18,2
        fcb     $00,$00  ; row 0
        fcb     $0C,$00  ; row 1
        fcb     $00,$00  ; row 2
        fcb     $0C,$00  ; row 3
        fcb     $00,$00  ; row 4
        fcb     $0C,$00  ; row 5
        fcb     $00,$00  ; row 6
        fcb     $0C,$00  ; row 7
        fcb     $00,$00  ; row 8
        fcb     $FC,$00  ; row 9
        fcb     $F0,$00  ; row 10
        fcb     $FC,$00  ; row 11
        fcb     $F0,$00  ; row 12
        fcb     $FC,$00  ; row 13
        fcb     $F0,$00  ; row 14
        fcb     $FC,$00  ; row 15
        fcb     $F0,$00  ; row 16
        fcb     $FC,$00  ; row 17
aops_A6EF_s1:  ; stencil pre-shifted right by sub=1px
        fcb     18,3
        fcb     $00,$00,$00  ; row 0
        fcb     $03,$00,$00  ; row 1
        fcb     $00,$00,$00  ; row 2
        fcb     $03,$00,$00  ; row 3
        fcb     $00,$00,$00  ; row 4
        fcb     $03,$00,$00  ; row 5
        fcb     $00,$00,$00  ; row 6
        fcb     $03,$00,$00  ; row 7
        fcb     $00,$00,$00  ; row 8
        fcb     $3F,$00,$00  ; row 9
        fcb     $3C,$00,$00  ; row 10
        fcb     $3F,$00,$00  ; row 11
        fcb     $3C,$00,$00  ; row 12
        fcb     $3F,$00,$00  ; row 13
        fcb     $3C,$00,$00  ; row 14
        fcb     $3F,$00,$00  ; row 15
        fcb     $3C,$00,$00  ; row 16
        fcb     $3F,$00,$00  ; row 17
aops_A6EF_s2:  ; stencil pre-shifted right by sub=2px
        fcb     18,3
        fcb     $00,$00,$00  ; row 0
        fcb     $00,$C0,$00  ; row 1
        fcb     $00,$00,$00  ; row 2
        fcb     $00,$C0,$00  ; row 3
        fcb     $00,$00,$00  ; row 4
        fcb     $00,$C0,$00  ; row 5
        fcb     $00,$00,$00  ; row 6
        fcb     $00,$C0,$00  ; row 7
        fcb     $00,$00,$00  ; row 8
        fcb     $0F,$C0,$00  ; row 9
        fcb     $0F,$00,$00  ; row 10
        fcb     $0F,$C0,$00  ; row 11
        fcb     $0F,$00,$00  ; row 12
        fcb     $0F,$C0,$00  ; row 13
        fcb     $0F,$00,$00  ; row 14
        fcb     $0F,$C0,$00  ; row 15
        fcb     $0F,$00,$00  ; row 16
        fcb     $0F,$C0,$00  ; row 17
aops_A6EF_s3:  ; stencil pre-shifted right by sub=3px
        fcb     18,3
        fcb     $00,$00,$00  ; row 0
        fcb     $00,$30,$00  ; row 1
        fcb     $00,$00,$00  ; row 2
        fcb     $00,$30,$00  ; row 3
        fcb     $00,$00,$00  ; row 4
        fcb     $00,$30,$00  ; row 5
        fcb     $00,$00,$00  ; row 6
        fcb     $00,$30,$00  ; row 7
        fcb     $00,$00,$00  ; row 8
        fcb     $03,$F0,$00  ; row 9
        fcb     $03,$C0,$00  ; row 10
        fcb     $03,$F0,$00  ; row 11
        fcb     $03,$C0,$00  ; row 12
        fcb     $03,$F0,$00  ; row 13
        fcb     $03,$C0,$00  ; row 14
        fcb     $03,$F0,$00  ; row 15
        fcb     $03,$C0,$00  ; row 16
        fcb     $03,$F0,$00  ; row 17
aops_A6A6_s0:  ; stencil pre-shifted right by sub=0px
        fcb     6,7
        fcb     $FF,$FF,$FF,$FF,$00,$00,$00  ; row 0
        fcb     $0F,$FF,$FF,$FF,$C0,$00,$00  ; row 1
        fcb     $03,$FF,$FF,$FF,$FF,$00,$00  ; row 2
        fcb     $00,$0F,$FF,$FF,$FF,$FC,$00  ; row 3
        fcb     $00,$03,$FF,$FF,$FF,$FF,$00  ; row 4
        fcb     $00,$00,$0F,$FF,$FF,$FF,$FC  ; row 5
aops_A6A6_s1:  ; stencil pre-shifted right by sub=1px
        fcb     6,8
        fcb     $3F,$FF,$FF,$FF,$C0,$00,$00,$00  ; row 0
        fcb     $03,$FF,$FF,$FF,$F0,$00,$00,$00  ; row 1
        fcb     $00,$FF,$FF,$FF,$FF,$C0,$00,$00  ; row 2
        fcb     $00,$03,$FF,$FF,$FF,$FF,$00,$00  ; row 3
        fcb     $00,$00,$FF,$FF,$FF,$FF,$C0,$00  ; row 4
        fcb     $00,$00,$03,$FF,$FF,$FF,$FF,$00  ; row 5
aops_A6A6_s2:  ; stencil pre-shifted right by sub=2px
        fcb     6,8
        fcb     $0F,$FF,$FF,$FF,$F0,$00,$00,$00  ; row 0
        fcb     $00,$FF,$FF,$FF,$FC,$00,$00,$00  ; row 1
        fcb     $00,$3F,$FF,$FF,$FF,$F0,$00,$00  ; row 2
        fcb     $00,$00,$FF,$FF,$FF,$FF,$C0,$00  ; row 3
        fcb     $00,$00,$3F,$FF,$FF,$FF,$F0,$00  ; row 4
        fcb     $00,$00,$00,$FF,$FF,$FF,$FF,$C0  ; row 5
aops_A6A6_s3:  ; stencil pre-shifted right by sub=3px
        fcb     6,8
        fcb     $03,$FF,$FF,$FF,$FC,$00,$00,$00  ; row 0
        fcb     $00,$3F,$FF,$FF,$FF,$00,$00,$00  ; row 1
        fcb     $00,$0F,$FF,$FF,$FF,$FC,$00,$00  ; row 2
        fcb     $00,$00,$3F,$FF,$FF,$FF,$F0,$00  ; row 3
        fcb     $00,$00,$0F,$FF,$FF,$FF,$FC,$00  ; row 4
        fcb     $00,$00,$00,$3F,$FF,$FF,$FF,$F0  ; row 5
aops_A684_s0:  ; stencil pre-shifted right by sub=0px
        fcb     2,4
        fcb     $00,$00,$00,$0F  ; row 0
        fcb     $00,$0F,$FF,$FF  ; row 1
aops_A684_s1:  ; stencil pre-shifted right by sub=1px
        fcb     2,5
        fcb     $00,$00,$00,$03,$C0  ; row 0
        fcb     $00,$03,$FF,$FF,$C0  ; row 1
aops_A684_s2:  ; stencil pre-shifted right by sub=2px
        fcb     2,5
        fcb     $00,$00,$00,$00,$F0  ; row 0
        fcb     $00,$00,$FF,$FF,$F0  ; row 1
aops_A684_s3:  ; stencil pre-shifted right by sub=3px
        fcb     2,5
        fcb     $00,$00,$00,$00,$3C  ; row 0
        fcb     $00,$00,$3F,$FF,$FC  ; row 1
aops_A85F_s0:  ; stencil pre-shifted right by sub=0px
        fcb     2,4
        fcb     $00,$00,$03,$C0  ; row 0
        fcb     $00,$3F,$FF,$C0  ; row 1
aops_A85F_s1:  ; stencil pre-shifted right by sub=1px
        fcb     2,5
        fcb     $00,$00,$00,$F0,$00  ; row 0
        fcb     $00,$0F,$FF,$F0,$00  ; row 1
aops_A85F_s2:  ; stencil pre-shifted right by sub=2px
        fcb     2,5
        fcb     $00,$00,$00,$3C,$00  ; row 0
        fcb     $00,$03,$FF,$FC,$00  ; row 1
aops_A85F_s3:  ; stencil pre-shifted right by sub=3px
        fcb     2,5
        fcb     $00,$00,$00,$0F,$00  ; row 0
        fcb     $00,$00,$FF,$FF,$00  ; row 1
aops_A68A_s0:  ; stencil pre-shifted right by sub=0px
        fcb     2,3
        fcb     $00,$3F,$FF  ; row 0
        fcb     $00,$00,$03  ; row 1
aops_A68A_s1:  ; stencil pre-shifted right by sub=1px
        fcb     2,4
        fcb     $00,$0F,$FF,$C0  ; row 0
        fcb     $00,$00,$00,$C0  ; row 1
aops_A68A_s2:  ; stencil pre-shifted right by sub=2px
        fcb     2,4
        fcb     $00,$03,$FF,$F0  ; row 0
        fcb     $00,$00,$00,$30  ; row 1
aops_A68A_s3:  ; stencil pre-shifted right by sub=3px
        fcb     2,4
        fcb     $00,$00,$FF,$FC  ; row 0
        fcb     $00,$00,$00,$0C  ; row 1
aops_A6C0_s0:  ; stencil pre-shifted right by sub=0px
        fcb     6,4
        fcb     $00,$FF,$FF,$FF  ; row 0
        fcb     $00,$03,$FF,$FF  ; row 1
        fcb     $00,$00,$FF,$FF  ; row 2
        fcb     $00,$00,$03,$FF  ; row 3
        fcb     $00,$00,$00,$FF  ; row 4
        fcb     $00,$00,$00,$03  ; row 5
aops_A6C0_s1:  ; stencil pre-shifted right by sub=1px
        fcb     6,5
        fcb     $00,$3F,$FF,$FF,$C0  ; row 0
        fcb     $00,$00,$FF,$FF,$C0  ; row 1
        fcb     $00,$00,$3F,$FF,$C0  ; row 2
        fcb     $00,$00,$00,$FF,$C0  ; row 3
        fcb     $00,$00,$00,$3F,$C0  ; row 4
        fcb     $00,$00,$00,$00,$C0  ; row 5
aops_A6C0_s2:  ; stencil pre-shifted right by sub=2px
        fcb     6,5
        fcb     $00,$0F,$FF,$FF,$F0  ; row 0
        fcb     $00,$00,$3F,$FF,$F0  ; row 1
        fcb     $00,$00,$0F,$FF,$F0  ; row 2
        fcb     $00,$00,$00,$3F,$F0  ; row 3
        fcb     $00,$00,$00,$0F,$F0  ; row 4
        fcb     $00,$00,$00,$00,$30  ; row 5
aops_A6C0_s3:  ; stencil pre-shifted right by sub=3px
        fcb     6,5
        fcb     $00,$03,$FF,$FF,$FC  ; row 0
        fcb     $00,$00,$0F,$FF,$FC  ; row 1
        fcb     $00,$00,$03,$FF,$FC  ; row 2
        fcb     $00,$00,$00,$0F,$FC  ; row 3
        fcb     $00,$00,$00,$03,$FC  ; row 4
        fcb     $00,$00,$00,$00,$0C  ; row 5
aops_A6D4_s0:  ; stencil pre-shifted right by sub=0px
        fcb     5,9
        fcb     $0F,$FC,$00,$3F,$FF,$FC,$00,$00,$00  ; row 0
        fcb     $00,$3F,$C0,$00,$00,$3F,$C0,$00,$00  ; row 1
        fcb     $00,$0F,$FC,$3F,$FF,$FF,$FC,$00,$00  ; row 2
        fcb     $00,$00,$3F,$F0,$00,$3F,$FF,$C0,$00  ; row 3
        fcb     $00,$00,$0F,$FF,$FF,$FF,$FF,$FC,$00  ; row 4
aops_A6D4_s1:  ; stencil pre-shifted right by sub=1px
        fcb     5,10
        fcb     $03,$FF,$00,$0F,$FF,$FF,$00,$00,$00,$00  ; row 0
        fcb     $00,$0F,$F0,$00,$00,$0F,$F0,$00,$00,$00  ; row 1
        fcb     $00,$03,$FF,$0F,$FF,$FF,$FF,$00,$00,$00  ; row 2
        fcb     $00,$00,$0F,$FC,$00,$0F,$FF,$F0,$00,$00  ; row 3
        fcb     $00,$00,$03,$FF,$FF,$FF,$FF,$FF,$00,$00  ; row 4
aops_A6D4_s2:  ; stencil pre-shifted right by sub=2px
        fcb     5,10
        fcb     $00,$FF,$C0,$03,$FF,$FF,$C0,$00,$00,$00  ; row 0
        fcb     $00,$03,$FC,$00,$00,$03,$FC,$00,$00,$00  ; row 1
        fcb     $00,$00,$FF,$C3,$FF,$FF,$FF,$C0,$00,$00  ; row 2
        fcb     $00,$00,$03,$FF,$00,$03,$FF,$FC,$00,$00  ; row 3
        fcb     $00,$00,$00,$FF,$FF,$FF,$FF,$FF,$C0,$00  ; row 4
aops_A6D4_s3:  ; stencil pre-shifted right by sub=3px
        fcb     5,10
        fcb     $00,$3F,$F0,$00,$FF,$FF,$F0,$00,$00,$00  ; row 0
        fcb     $00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00  ; row 1
        fcb     $00,$00,$3F,$F0,$FF,$FF,$FF,$F0,$00,$00  ; row 2
        fcb     $00,$00,$00,$FF,$C0,$00,$FF,$FF,$00,$00  ; row 3
        fcb     $00,$00,$00,$3F,$FF,$FF,$FF,$FF,$F0,$00  ; row 4
aops_archfill1_s0:  ; stencil pre-shifted right by sub=0px
        fcb     6,2
        fcb     $FF,$C0  ; row 0
        fcb     $FF,$C0  ; row 1
        fcb     $FF,$C0  ; row 2
        fcb     $FF,$C0  ; row 3
        fcb     $FF,$C0  ; row 4
        fcb     $FF,$C0  ; row 5
aops_archfill1_s1:  ; stencil pre-shifted right by sub=1px
        fcb     6,3
        fcb     $3F,$F0,$00  ; row 0
        fcb     $3F,$F0,$00  ; row 1
        fcb     $3F,$F0,$00  ; row 2
        fcb     $3F,$F0,$00  ; row 3
        fcb     $3F,$F0,$00  ; row 4
        fcb     $3F,$F0,$00  ; row 5
aops_archfill1_s2:  ; stencil pre-shifted right by sub=2px
        fcb     6,3
        fcb     $0F,$FC,$00  ; row 0
        fcb     $0F,$FC,$00  ; row 1
        fcb     $0F,$FC,$00  ; row 2
        fcb     $0F,$FC,$00  ; row 3
        fcb     $0F,$FC,$00  ; row 4
        fcb     $0F,$FC,$00  ; row 5
aops_archfill1_s3:  ; stencil pre-shifted right by sub=3px
        fcb     6,3
        fcb     $03,$FF,$00  ; row 0
        fcb     $03,$FF,$00  ; row 1
        fcb     $03,$FF,$00  ; row 2
        fcb     $03,$FF,$00  ; row 3
        fcb     $03,$FF,$00  ; row 4
        fcb     $03,$FF,$00  ; row 5

arch_stencil_tbl:  ; {fdb cel; fdb s0; fdb s1; fdb s2; fdb s3}, 0-terminated
        fdb     scene6_bg_A707
        fdb     aops_A707_s0,aops_A707_s1,aops_A707_s2,aops_A707_s3
        fdb     scene6_bg_A82B
        fdb     aops_A82B_s0,aops_A82B_s1,aops_A82B_s2,aops_A82B_s3
        fdb     scene6_bg_A7D1
        fdb     aops_A7D1_s0,aops_A7D1_s1,aops_A7D1_s2,aops_A7D1_s3
        fdb     scene6_bg_A763
        fdb     aops_A763_s0,aops_A763_s1,aops_A763_s2,aops_A763_s3
        fdb     scene6_bg_A865
        fdb     aops_A865_s0,aops_A865_s1,aops_A865_s2,aops_A865_s3
        fdb     scene6_bg_A877
        fdb     aops_A877_s0,aops_A877_s1,aops_A877_s2,aops_A877_s3
        fdb     scene6_bg_A87B
        fdb     aops_A87B_s0,aops_A87B_s1,aops_A87B_s2,aops_A87B_s3
        fdb     scene6_bg_A6EF
        fdb     aops_A6EF_s0,aops_A6EF_s1,aops_A6EF_s2,aops_A6EF_s3
        fdb     scene6_bg_A6A6
        fdb     aops_A6A6_s0,aops_A6A6_s1,aops_A6A6_s2,aops_A6A6_s3
        fdb     scene6_bg_A684
        fdb     aops_A684_s0,aops_A684_s1,aops_A684_s2,aops_A684_s3
        fdb     scene6_bg_A85F
        fdb     aops_A85F_s0,aops_A85F_s1,aops_A85F_s2,aops_A85F_s3
        fdb     scene6_bg_A68A
        fdb     aops_A68A_s0,aops_A68A_s1,aops_A68A_s2,aops_A68A_s3
        fdb     scene6_bg_A6C0
        fdb     aops_A6C0_s0,aops_A6C0_s1,aops_A6C0_s2,aops_A6C0_s3
        fdb     scene6_bg_A6D4
        fdb     aops_A6D4_s0,aops_A6D4_s1,aops_A6D4_s2,aops_A6D4_s3
        fdb     scene6_bg_archfill1
        fdb     aops_archfill1_s0,aops_archfill1_s1,aops_archfill1_s2,aops_archfill1_s3
        fdb     0                       ; end
