* tests/scripted/scene6_cliff.s  — GENERATED by harness/tools/gen_scene6_cliff.py
* STATIC climb-tableau cliff/scenery + player start-pose. include-only.
* Composite order (driver): backdrop -> THIS (cliff/scenery -> start-pose) -> player-HUD.
* Positions = traced climb draw cols/rows -> CoCo3 (+20px centered, +leading-trim).
* ---------------------------------------------------------------

* draw_climb_scenery — cliff face ($AB8E striations) + structure + base + mountain
*   band, table-driven. Transparent blit (index-0 keys to the backdrop behind).
draw_climb_scenery:
        ldy     #climb_scn_tbl
dcs_loop:
        ldx     ,y++                    ; X = cel ptr (0 = end)
        beq     dcs_done
        lda     ,y+                     ; sub-byte
        sta     <blit_subbyte
        lda     ,y+                     ; A = byte col
        ldb     ,y+                     ; B = row
        pshs    y
        jsr     HAL_gfx_blit_sprite
        puls    y
        bra     dcs_loop
dcs_done:
        rts

* draw_climb_startpose — the 2-part crawl-start pose: legs $A3E9 (Y158) then
*   torso $A3C5 over it. Drawn AFTER scenery so the player is on top of the cliff.
draw_climb_startpose:
        lda     #3
        sta     <blit_subbyte
        lda     #21                     ; byte col
        ldb     #158                    ; row (Y=158)
        ldx     #scene6_climb_A3E9
        jsr     HAL_gfx_blit_sprite
        lda     #2
        sta     <blit_subbyte
        lda     #22                     ; byte col
        ldb     #141                    ; row (Y=141)
        ldx     #scene6_climb_A3C5
        jsr     HAL_gfx_blit_sprite
        rts

climb_scn_tbl:
        fdb     scene6_cliff_AB8E
        fcb     2,22,117
        fdb     scene6_cliff_AB8E
        fcb     2,22,119
        fdb     scene6_cliff_AB8E
        fcb     2,22,121
        fdb     scene6_cliff_AB8E
        fcb     2,22,123
        fdb     scene6_cliff_AB8E
        fcb     2,22,125
        fdb     scene6_cliff_AB8E
        fcb     2,22,127
        fdb     scene6_cliff_AB8E
        fcb     2,22,129
        fdb     scene6_cliff_AB8E
        fcb     2,22,131
        fdb     scene6_cliff_AB8E
        fcb     2,22,133
        fdb     scene6_cliff_AB8E
        fcb     2,22,135
        fdb     scene6_cliff_AB8E
        fcb     2,22,137
        fdb     scene6_cliff_AB8E
        fcb     2,22,139
        fdb     scene6_cliff_AB8E
        fcb     2,22,141
        fdb     scene6_cliff_AB8E
        fcb     2,22,143
        fdb     scene6_cliff_AB8E
        fcb     2,22,145
        fdb     scene6_cliff_AB8E
        fcb     2,22,147
        fdb     scene6_cliff_AB8E
        fcb     2,22,149
        fdb     scene6_cliff_AB8E
        fcb     2,22,151
        fdb     scene6_cliff_AB94
        fcb     2,22,112
        fdb     scene6_cliff_AB7C
        fcb     2,22,104
        fdb     scene6_cliff_AB4A
        fcb     0,5,112
        fdb     scene6_cliff_AA7D
        fcb     2,15,152
        fdb     scene6_cliff_AA23
        fcb     3,25,100
        fdb     scene6_cliff_AA23
        fcb     3,46,100
        fdb     scene6_cliff_AA23
        fcb     3,67,100
        fdb     scene6_cliff_AA31
        fcb     3,24,100
        fdb     scene6_cliff_AA31
        fcb     3,45,100
        fdb     scene6_cliff_AA31
        fcb     3,66,100
        fdb     0                       ; end

* --- cel data (single source) ---
        include "../../content/scenery/scene6_cliff_AA23/converted.s"
        include "../../content/scenery/scene6_cliff_AA31/converted.s"
        include "../../content/scenery/scene6_cliff_AA7D/converted.s"
        include "../../content/scenery/scene6_cliff_AB4A/converted.s"
        include "../../content/scenery/scene6_cliff_AB7C/converted.s"
        include "../../content/scenery/scene6_cliff_AB8E/converted.s"
        include "../../content/scenery/scene6_cliff_AB94/converted.s"
        include "../../content/player/scene6_climb_A3C5/converted.s"
        include "../../content/player/scene6_climb_A3E9/converted.s"

