* tests/scripted/scene6_cliff.s  — GENERATED by harness/tools/gen_scene6_cliff.py
* STATIC climb-tableau cliff/scenery + player start-pose. include-only.
* Composite order (driver): backdrop -> THIS (cliff/scenery -> start-pose) -> player-HUD.
* Positions = traced climb draw cols/rows -> CoCo3 (+20px centered, +leading-trim).
* ---------------------------------------------------------------

* draw_climb_scenery_back — wall-top posts drawn BEFORE the Fuji, so the
*   mountain occludes their upper rows (oracle order: AA31 -> Fuji -> ...).
draw_climb_scenery_back:
        ldy     #climb_scn_back_tbl
dcsb_loop:
        ldx     ,y++
        beq     dcsb_done
        lda     ,y+
        sta     <blit_subbyte
        lda     ,y+
        ldb     ,y+
        pshs    y
        jsr     HAL_gfx_blit_sprite_opaque
        puls    y
        bra     dcsb_loop
dcsb_done:
        rts

* draw_climb_scenery — wall-top FRONT layer (AA23 posts + AB rails) + AA7D base,
*   drawn AFTER the Fuji. OPAQUE blit (black is solid). [Jay gate 2026-07-12]
draw_climb_scenery:
        ldy     #climb_scn_tbl
dcs_loop:
        ldx     ,y++                    ; X = cel ptr (0 = end)
        beq     dcs_done
        lda     ,y+                     ; sub-byte
        sta     <blit_subbyte
        lda     ,y+                     ; A = byte col
        ldb     ,y+                     ; B = row
        pshs    y
        jsr     HAL_gfx_blit_sprite_opaque
        puls    y
        bra     dcs_loop
dcs_done:
        rts

* draw_climb_startpose — the 2-part crawl-start pose: legs $A3E9 (Y158) then
*   torso $A3C5 over it. Drawn AFTER scenery so the player is on top of the cliff.
draw_climb_startpose:
        lda     #3
        sta     <blit_subbyte
        lda     #21                     ; byte col
        ldb     #158                    ; row (Y=158)
        ldx     #scene6_climb_A3E9
        jsr     HAL_gfx_blit_sprite
        lda     #2
        sta     <blit_subbyte
        lda     #22                     ; byte col
        ldb     #141                    ; row (Y=141)
        ldx     #scene6_climb_A3C5
        jsr     HAL_gfx_blit_sprite
        rts

climb_scn_back_tbl:
        fdb     scene6_cliff_AA31
        fcb     0,24,100
        fdb     scene6_cliff_AA31
        fcb     0,45,100
        fdb     scene6_cliff_AA31
        fcb     0,66,100
        fdb     0                       ; end

climb_scn_tbl:
        fdb     scene6_cliff_AA23
        fcb     0,25,100
        fdb     scene6_cliff_AA23
        fcb     0,46,100
        fdb     scene6_cliff_AA23
        fcb     0,67,100
        fdb     scene6_cliff_AB4A
        fcb     0,5,112
        fdb     scene6_cliff_AB7C
        fcb     0,22,104
        fdb     scene6_cliff_AB94
        fcb     0,22,112
        fdb     scene6_cliff_AA7D
        fcb     0,15,152
        fdb     0                       ; end

* --- cel data (single source) ---
        include "../../content/scenery/scene6_cliff_AA23/converted.s"
        include "../../content/scenery/scene6_cliff_AA31/converted.s"
        include "../../content/scenery/scene6_cliff_AA7D/converted.s"
        include "../../content/scenery/scene6_cliff_AB4A/converted.s"
        include "../../content/scenery/scene6_cliff_AB7C/converted.s"
        include "../../content/scenery/scene6_cliff_AB94/converted.s"
        include "../../content/player/scene6_climb_A3C5/converted.s"
        include "../../content/player/scene6_climb_A3E9/converted.s"

