* tests/scripted/scene6_placement_gen.s — GENERATED by harness/tools/gen_scene6_placement.py
*   from content/scene6/scene6_placement.txt. DO NOT EDIT. Edit the text-source, re-run the codegen.
*   The single-home (§2F) scene-6 placement table the build reads. include-only; no org.
* --- registry: reg_<id> = fcb w, h, start_col (start_col promoted from the cel comment) ---
reg_AA7D:  fcb 11,29,42   ; w, h, start_col
reg_AB4A:  fcb 20,4,0   ; w, h, start_col
reg_AB7C:  fcb 4,8,70   ; w, h, start_col
reg_AB94:  fcb 3,4,70   ; w, h, start_col
reg_AA23:  fcb 1,12,79   ; w, h, start_col
reg_AA31:  fcb 2,12,79   ; w, h, start_col
reg_A9E2:  fcb 27,3,0   ; w, h, start_col
reg_A9B8:  fcb 18,4,0   ; w, h, start_col
reg_A976:  fcb 14,8,0   ; w, h, start_col
reg_A948:  fcb 7,11,0   ; w, h, start_col
reg_A3C5:  fcb 4,17,0   ; w, h, start_col
reg_A3E9:  fcb 6,8,0   ; w, h, start_col
* --- placement: plc_<id> = fcb x, y (resolved placed col,row) ---
plc_AB4A:  fcb 5,112   ; AB4A: col, row
plc_A9E2:  fcb 26,108   ; A9E2: col, row
plc_A9B8:  fcb 31,100   ; A9B8: col, row
plc_A976:  fcb 33,92   ; A976: col, row
plc_A948:  fcb 36,81   ; A948: col, row
plc_AA7D:  fcb 15,152   ; AA7D: col, row
plc_AB7C:  fcb 22,104   ; AB7C: col, row
plc_AB94:  fcb 22,112   ; AB94: col, row
plc_AA31_0:  fcb 24,100   ; AA31: col, row
plc_AA31_1:  fcb 45,100   ; AA31: col, row
plc_AA31_2:  fcb 66,100   ; AA31: col, row
plc_AA23_0:  fcb 25,100   ; AA23: col, row
plc_AA23_1:  fcb 46,100   ; AA23: col, row
plc_AA23_2:  fcb 67,100   ; AA23: col, row
plc_A3E9:  fcb 21,158   ; A3E9: col, row
plc_A3C5:  fcb 22,141   ; A3C5: col, row
