* tests/scripted/scene6_climb_anim_gen.s — GENERATED by harness/tools/gen_scene6_placement.py
*   from content/scene6/scene6_placement.txt [climb_anim]. DO NOT EDIT. Edit the text-source.
*   The §2F single-home climb crawl animation table. Read by src/engine/climb_controller.s;
*   included ONLY by the crawl drivers (it references the 15 climb cels). include-only; no org.
*   frame block = {fcb dwell, pcnt; per part: fdb cel; fcb col,sub,row}.
cl_frames:
        fdb     cl_f0,cl_f1,cl_f2,cl_f3,cl_f4,cl_f5,cl_f6
cl_f0:  fcb     21,2
        fdb     scene6_climb_A3E9
        fcb     21,3,158
        fdb     scene6_climb_A3C5
        fcb     22,2,141
cl_f1:  fcb     7,2
        fdb     scene6_climb_A425
        fcb     22,2,148
        fdb     scene6_climb_A40B
        fcb     24,1,140
cl_f2:  fcb     7,2
        fdb     scene6_climb_A4A4
        fcb     22,2,143
        fdb     scene6_climb_A45A
        fcb     26,0,139
cl_f3:  fcb     7,2
        fdb     scene6_climb_A4F2
        fcb     22,2,143
        fdb     scene6_climb_A4D2
        fcb     24,1,137
cl_f4:  fcb     7,2
        fdb     scene6_climb_A572
        fcb     22,2,141
        fdb     scene6_climb_A548
        fcb     24,1,131
cl_f5:  fcb     7,2
        fdb     scene6_climb_A5DC
        fcb     24,1,127
        fdb     scene6_climb_A5CC
        fcb     26,0,120
cl_f6:  fcb     60,3
        fdb     scene6_player_899C
        fcb     25,2,138
        fdb     scene6_player_8ACB
        fcb     25,2,124
        fdb     scene6_player_8E9B
        fcb     26,0,116
