* tests/scripted/scene6_climb_opacity_gen.s — GENERATED by harness/tools/gen_climb_opacity.py
*   opacity descriptors for AUTHORED climb cels (read from their opacity.s sidecars on disk)
*   + cl_opacity_tbl the climb draw path scans. DO NOT EDIT. include-only; no org.

op_A3E9:  ; stencil (2D mask, pre-shifted right by sub=3 px for byte-aligned punch)
        fcb     8,7
        fcb     $00,$0F,$FC,$00,$00,$00,$00  ; row 0
        fcb     $00,$00,$3F,$00,$00,$00,$00  ; row 1
        fcb     $00,$00,$00,$00,$00,$00,$00  ; row 2
        fcb     $00,$00,$00,$00,$00,$00,$00  ; row 3
        fcb     $00,$00,$00,$00,$00,$00,$00  ; row 4
        fcb     $00,$00,$00,$00,$00,$00,$00  ; row 5
        fcb     $00,$00,$00,$00,$00,$00,$00  ; row 6
        fcb     $00,$00,$00,$00,$00,$00,$00  ; row 7
op_A3C5:  ; mixed (full-sprite coverage; rides sub-byte via the underlying blits)
        fcb     0,1,16,1,1
        fcb     0,2,3,1,0
        fcb     0,4,0,3,0
        fcb     0,4,4,12,0
        fcb     1,3,16,1,0
        fcb     2,1,3,1,1
        fcb     3,1,3,1,0
        fcb     0,0,0,0,0

cl_opacity_tbl:  ; {fdb cel; fcb type(1=mixed,2=masked,3=stencil); fdb desc}, term fdb 0
        fdb     scene6_climb_A3E9
        fcb     3
        fdb     op_A3E9
        fdb     scene6_climb_A3C5
        fcb     1
        fdb     op_A3C5
        fdb     0                       ; end
