* tests/scripted/scene6_cliff.s  — GENERATED by harness/tools/gen_scene6_cliff.py
* STATIC climb-tableau cliff/scenery + player start-pose. include-only.
* Composite order (driver): backdrop -> THIS (cliff/scenery -> start-pose) -> player-HUD.
* Positions = traced climb draw cols/rows -> CoCo3 (+20px centered, +leading-trim).
* ---------------------------------------------------------------

* draw_climb_scenery_back — wall-top posts drawn BEFORE the Fuji, so the
*   mountain occludes their upper rows (oracle order: AA31 -> Fuji -> ...).
* table entry = fdb cel ; fdb plc_ptr (§2F: placement value lives ONCE in plc_<id>).
draw_climb_scenery_back:
        ldy     #climb_scn_back_tbl
dcsb_loop:
        ldx     ,y++                    ; X = cel ptr (0 = end)
        beq     dcsb_done
        ldu     ,y++                    ; U -> plc_ row (col,sub,row) — §2F single home
        lda     1,u                     ; sub
        sta     <blit_subbyte
        lda     ,u                      ; col
        ldb     2,u                     ; row
        pshs    y
        jsr     HAL_gfx_blit_sprite_opaque
        puls    y
        bra     dcsb_loop
dcsb_done:
        rts

* draw_climb_scenery — wall-top FRONT layer (AA23 posts + AB rails) + AA7D base,
*   drawn AFTER the Fuji. OPAQUE blit (black is solid). [Jay gate 2026-07-12]
draw_climb_scenery:
        ldy     #climb_scn_tbl
dcs_loop:
        ldx     ,y++                    ; X = cel ptr (0 = end)
        beq     dcs_done
        ldu     ,y++                    ; U -> plc_ row (col,sub,row) — §2F single home
        lda     1,u                     ; sub-byte
        sta     <blit_subbyte
        lda     ,u                      ; A = byte col
        ldb     2,u                     ; B = row
        pshs    y
        jsr     HAL_gfx_blit_sprite_opaque
        puls    y
        bra     dcs_loop
dcs_done:
        rts

* draw_climb_startpose — the 2-part crawl-start pose: legs $A3E9 (Y158) then
*   torso $A3C5 over it. Drawn AFTER scenery so the player is on top of the cliff.
*   placement single-homed in plc_start_<cel> (derived from [animation] climb_crawl f0).
draw_climb_startpose:
        lda     plc_start_A3E9+1         ; sub
        sta     <blit_subbyte
        lda     plc_start_A3E9           ; col
        ldb     plc_start_A3E9+2         ; row
        ldx     #scene6_climb_A3E9
        jsr     HAL_gfx_blit_sprite
        lda     plc_start_A3C5+1         ; sub
        sta     <blit_subbyte
        lda     plc_start_A3C5           ; col
        ldb     plc_start_A3C5+2         ; row
        ldx     #scene6_climb_A3C5
        jsr     HAL_gfx_blit_sprite
        rts

climb_scn_back_tbl:                     ; fdb cel, plc_ptr
        fdb     scene6_cliff_AA31,plc_AA31_0
        fdb     scene6_cliff_AA31,plc_AA31_1
        fdb     scene6_cliff_AA31,plc_AA31_2
        fdb     0                       ; end

climb_scn_tbl:                          ; fdb cel, plc_ptr
        fdb     scene6_cliff_AA23,plc_AA23_0
        fdb     scene6_cliff_AA23,plc_AA23_1
        fdb     scene6_cliff_AA23,plc_AA23_2
        fdb     scene6_cliff_AB4A,plc_AB4A
        fdb     scene6_cliff_AB7C,plc_AB7C
        fdb     scene6_cliff_AB94,plc_AB94
        fdb     scene6_cliff_AA7D,plc_AA7D
        fdb     0                       ; end

* --- cel data (single source) ---
        include "../../content/scenery/scene6_cliff_AA23/converted.s"
        include "../../content/scenery/scene6_cliff_AA31/converted.s"
        include "../../content/scenery/scene6_cliff_AA7D/converted.s"
        include "../../content/scenery/scene6_cliff_AB4A/converted.s"
        include "../../content/scenery/scene6_cliff_AB7C/converted.s"
        include "../../content/scenery/scene6_cliff_AB94/converted.s"
        include "../../content/player/scene6_climb_A3C5/converted.s"
        include "../../content/player/scene6_climb_A3E9/converted.s"

