* opacity descriptor (mixed) for scene6_climb_A3C5 — GENERATED by sprite_tool.
*   matches HAL_gfx_blit_sprite_mixed: fcb start_col,width,start_row,num_rows,opaque.
scene6_climb_A3C5_opacity_mixed:
        fcb     0,1,16,1,1
        fcb     0,2,3,1,0
        fcb     0,4,0,3,0
        fcb     0,4,4,12,0
        fcb     1,3,16,1,0
        fcb     2,1,3,1,1
        fcb     3,1,3,1,0
        fcb     0,0,0,0,0      ; terminator (width byte 0)
