#!/usr/bin/env python3
"""bake_scene4.py — bake the scene-4 scrolling-narrative text into per-line
packed glyph tables for the CoCo3 VOFFSET scroll (R-p26).

Source of truth: karateka_dissasembly_claude/src/text_strings.s string
indices 4..21 (the scrolling narrative). All narrative descriptors have
init position (byteX=0, subbyteX=0) — i.e. LEFT-ALIGNED at Apple X=0.
Per §19, Apple px 0 -> CoCo3 px 20 (byte 5, sub 0); 1:1 scale thereafter.

Pen model (oracle text_render.s / font_metrics.s — the R-p25 correction):
draw glyph at pen, then pen += xstep(glyph). Space ('`') advances 7px and
draws nothing. This is the SAME model bake_text.py uses for scenes 2-3;
here it runs LEFT-aligned from CoCo3 px 20 instead of centered.

Output: per-line tables {fdb glyph_addr ; fcb byte_col, subbyte} (NO row —
the scroll engine supplies the row when it blits the line into the ring
buffer), a per-line count, and an 18-slot master table (ptr,count) that
includes the 2 blank paragraph-break slots (oracle indices 11 and 16).
"""

# Oracle X-advance in pixels (font_glyph_xstep_byte*7 + subbyte), font_metrics.s
XSTEP = {
    ' ': 7, 'a': 8, 'b': 10, 'c': 9, 'd': 9, 'e': 9, 'f': 7, 'g': 9, 'h': 10,
    'i': 4, 'j': 6, 'k': 9, 'l': 7, 'm': 14, 'n': 10, 'o': 10, 'p': 11,
    'q': 11, 'r': 11, 's': 8, 't': 10, 'u': 10, 'v': 11, 'w': 17, 'x': 10,
    'y': 10, 'z': 10, '.': 7, ',': 3, ':': 7, '-': 7,
}
# glyph -> converted CoCo3 label
LABEL = {c: f'glyph_{c}_coco3' for c in 'abcdefghijklmnopqrstuvwxyz'}
LABEL.update({'.': 'glyph_period_coco3', ',': 'glyph_comma_coco3',
              ':': 'glyph_colon_coco3', '-': 'glyph_hyphen_coco3'})

LEFT_PX = 20  # Apple X=0 -> CoCo3 px 20 (§19 +20 border)

# Scene-4 narrative, oracle indices 4..21 (text_strings.s). None=blank slot.
LINES = [
    "high atop a craggy cliff, guarded",      # idx 4
    "by an army of fierce warriors,",         # idx 5
    "stands the fortress of the evil",        # idx 6
    "warlord akuma.  deep in the",            # idx 7
    "darkest dungeon of the castle,",         # idx 8
    "akuma gloats over his lovely",           # idx 9
    "captive, the princess mariko.",          # idx 10
    None,                                     # idx 11 (blank paragraph break)
    "you are one trained in the way",         # idx 12
    "of karate: a karateka.  alone and",      # idx 13
    "unarmed, you must defeat akuma",         # idx 14
    "and rescue the beautiful mariko.",       # idx 15
    None,                                     # idx 16 (blank paragraph break)
    "put fear and self-concern behind",       # idx 17
    "you.  focus your will on your",          # idx 18
    "objective, accepting death as a",        # idx 19
    "possibility.  this is the way of",       # idx 20
    "the karateka.",                          # idx 21
]


def bake_line(text):
    """Return list of (label, byte_col, subbyte) for one left-aligned line."""
    pen = LEFT_PX
    out = []
    for ch in text:
        if ch != ' ':
            out.append((LABEL[ch], pen // 4, pen % 4))
        pen += XSTEP[ch]
    return out


def emit():
    L = []
    L.append("* src/engine/scene4_text.s  [R-p26 — GENERATED by tools/bake_scene4.py]")
    L.append("* Scene-4 scrolling-narrative per-line glyph tables.")
    L.append("* Oracle text_strings.s indices 4..21 (left-aligned, Apple X=0 -> CoCo3 px 20).")
    L.append("* Pen model: byte=px//4, sub=px%4, pen += oracle xstep. Row supplied by the")
    L.append("* scroll engine (NOT baked). Blank slots (idx 11/16) = count 0, ptr 0.")
    L.append("* ---------------------------------------------------------------")
    L.append("")
    # per-line tables
    for i, text in enumerate(LINES):
        if text is None:
            continue
        entries = bake_line(text)
        L.append(f'* line {i:2d}: "{text}"  ({len(entries)} glyphs)')
        L.append(f's4_line{i:02d}_tbl:')
        for label, byte, sub in entries:
            L.append(f'        fdb     {label}')
            L.append(f'        fcb     {byte},{sub}')
        L.append("")
    # master 18-slot table: fdb table_ptr ; fcb count   (blank: fdb 0 ; fcb 0)
    L.append("* Master slot table — 18 line-slots in scroll order (blanks included).")
    L.append("* Entry: fdb table_ptr ; fcb glyph_count.")
    L.append("s4_slots:")
    for i, text in enumerate(LINES):
        if text is None:
            L.append(f'        fdb     0')
            L.append(f'        fcb     0          ; slot {i:2d}: blank paragraph break')
        else:
            n = len(bake_line(text))
            L.append(f'        fdb     s4_line{i:02d}_tbl')
            L.append(f'        fcb     {n}          ; slot {i:2d}')
    L.append("")
    L.append("S4_SLOT_COUNT   equ     18")
    L.append("")
    return "\n".join(L) + "\n"


if __name__ == '__main__':
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == '--emit':
        sys.stdout.write(emit())
    else:
        # summary
        for i, t in enumerate(LINES):
            if t is None:
                print(f'slot {i:2d}: <blank>')
            else:
                e = bake_line(t)
                print(f'slot {i:2d}: {len(e):2d} glyphs  first@byte{e[0][1]}.{e[0][2]} '
                      f'last@byte{e[-1][1]}.{e[-1][2]}  "{t}"')
