#!/usr/bin/env python3
"""
sidecar.py — the opacity descriptor companion file (beside converted.s).

Written where a cel has OPAQUE (shadow) work; the build includes it and blits via
HAL_gfx_blit_sprite_mixed / _masked. NO pixel-format change: converted.s stays 2bpp.

File: <cel_dir>/opacity.s
  mixed : <label>_opacity_mixed:   fcb start_col,width,start_row,num_rows,opaque  ... ; term fcb 0,0,0,0,0
  masked: <label>_opacity_mask:    fcb $XX,...   (width bytes, 11=opaque/00=keyed)
The label suffix (_opacity_mixed / _opacity_mask) records the KIND unambiguously.
"""
import os, re

NAME = "opacity.s"

def path_for(cel_dir):
    return os.path.join(cel_dir, NAME)

def write_sidecar(cel_dir, label, kind, payload):
    p = path_for(cel_dir)
    if kind == 'mixed':
        lines = [f"* opacity descriptor (mixed) for {label} — GENERATED by sprite_tool.",
                 f"*   matches HAL_gfx_blit_sprite_mixed: fcb start_col,width,start_row,num_rows,opaque.",
                 f"{label}_opacity_mixed:"]
        for sc, w, sr, nr, op in payload:
            lines.append(f"        fcb     {sc},{w},{sr},{nr},{op}")
        lines.append("        fcb     0,0,0,0,0      ; terminator (width byte 0)")
    elif kind == 'masked':
        hexv = ','.join(f'${b:02X}' for b in payload)
        lines = [f"* opacity descriptor (masked) for {label} — GENERATED by sprite_tool.",
                 f"*   matches HAL_gfx_blit_sprite_masked: one mask byte/column (11=opaque,00=keyed).",
                 f"{label}_opacity_mask:",
                 f"        fcb     {hexv}"]
    else:
        raise ValueError(f"no sidecar for kind {kind}")
    with open(p, 'w', newline='') as f:
        f.write('\r\n'.join(lines) + '\r\n')
    return p

def read_sidecar(cel_dir):
    """Return ('mixed', rects) | ('masked', mask) | None. Parseable-check for the lint."""
    p = path_for(cel_dir)
    if not os.path.exists(p):
        return None
    txt = open(p, newline='').read()
    fcb = [l.split(';', 1)[0] for l in txt.splitlines() if re.search(r'^\s*fcb\s', l)]
    if '_opacity_mixed:' in txt:
        rects = []
        for l in fcb:
            nums = [int(v) for v in re.findall(r'\b(\d+)\b', l)]
            if len(nums) >= 5 and nums[1] != 0:            # width!=0 (skip terminator)
                rects.append(tuple(nums[:5]))
        return 'mixed', rects
    if '_opacity_mask:' in txt:
        mask = []
        for l in fcb:
            mask += [int(v, 16) for v in re.findall(r'\$([0-9A-Fa-f]{2})', l)]
        return 'masked', mask
    raise ValueError(f"{p}: unrecognized opacity sidecar")

def remove_sidecar(cel_dir):
    p = path_for(cel_dir)
    if os.path.exists(p):
        os.remove(p)
        return True
    return False
